SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Huh?\n"
    .string "Team Rocket is gone?$"

SilphCo_4F_Text_Grunt1Intro:: @ 8175A2F
    .string "Team Rocket has taken control\n"
    .string "of Silph Co.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Fwahahaha!\n"
    .string "My Boss has been after this place!$"

SilphCo_4F_Text_RodneyIntro:: @ 8175A90
    .string "My Pokémon is my loyal servant.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Darn!\n"
    .string "You weak Pokémon!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a Card Key to open the\n"
    .string "doors here.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Intruder spotted!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Who are you?$"

SilphCo_4F_Text_Grunt2PostBattle:: @ 8175B38
    .string "I better tell the Boss on 11F!$"

SilphCo_4F_Text_FloorSign:: @ 8175B57
    .string "Silph Co. Head Office\n"
    .string "4F$"

