RockTunnel_B1F_Text_SofiaIntro::
    .string "Do you know how you can avoid\n"
    .string "getting lost in the mountains?\p"
    .string "You can bend twigs as trail\n"
    .string "markers.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Oh well!\n"
    .string "I did my best!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "Time to go home!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Can you beat my power?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Oof!\n"
    .string "Outmuscled!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "I go for power because I've\n"
    .string "always been a big guy.$"

RockTunnel_B1F_Text_CooperIntro:: @ 817973A
    .string "You have a Pokédex?\n"
    .string "I want one, too.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Shit!\n"
    .string "I'm so jealous!$"

RockTunnel_B1F_Text_CooperPostBattle:: @ 8179777
    .string "When you finish your Pokédex,\n"
    .string "can I have it?$"

RockTunnel_B1F_Text_SteveIntro:: @ 81797A4
    .string "Um… Do you know about Pokémon\n"
    .string "cosplay?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "UwU, that's that.$"

RockTunnel_B1F_Text_StevePostBattle:: @ 81797DE
    .string "Pokémon cosplay is dressing up as\n"
    .string "Pokémon for fun.\p"
    .string "Clefairy is a favorite.$"

RockTunnel_B1F_Text_AllenIntro:: @ 8179829
    .string "My Pokémon techniques will leave\n"
    .string "you weak!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "I give!\n"
    .string "You're a better technician!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "In the mountains, you'll often\n"
    .string "find Rock-type Pokémon.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "I don't usually battle on a first\n"
    .string "date. But, I'll make an exception.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Oh, no!\n"
    .string "I lost!$"

RockTunnel_B1F_Text_MarthaPostBattle:: @ 81798E9
    .string "Do you want my number?\n"
    .string "No? Aw, ok...$"

RockTunnel_B1F_Text_EricIntro::
    .string "Hit me with your best shot!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Fired away!$"

RockTunnel_B1F_Text_EricPostBattle:: @ 817993E
    .string "What can I say? I like Pat\n"
    .string "Benatar.$"

RockTunnel_B1F_Text_WinstonIntro:: @ 8179968
    .string "I draw illustrations of Pokémon\n"
    .string "when I'm home.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Whew…\n"
    .string "I'm pooped…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "I'm an artist, not a fighter.\n"
    .string "I'll go home and draw.$"

