CeladonCity_Condominiums_1F_Text_Meowth:: @ 81960BB
    .string "Meowth: Meowth!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on booze.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "Tea.\p"
    .string "It's the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany:: @ 8196148
    .string "My Pokémon keep me company.\n"
    .string "Meowth even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, sweetie.\n"
    .string "Did you enjoy my Tea?\p"
    .string "Are you, by any chance,\n"
    .string "From Pallet Town?\p"
    .string "A girl from Pallet Town, Daisy,\n"
    .string "she enjoys Tea like me.\p"
    .string "She visits the Celadon Dept. Store\n"
    .string "to buy some.$"

CeladonCity_Condominiums_1F_Text_Clefairy:: @ 819625B
    .string "Clefairy: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran:: @ 8196272
    .string "Nidoran♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite:: @ 8196287
    .string "Celadon Mansion\n"
    .string "Manager's Suite$"

