MtMoon_1F_Text_MarcosIntro:: @ 817279D
    .string "Whoa!\n"
    .string "You shocked me!\l"
    .string "You gotta be more careful!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Woah!\n"
    .string "Shocked again!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "You really shouldn't be\n"
    .string "wandering around here in the dark.$"

MtMoon_1F_Text_JoshIntro::
    .string "Did you come to explore the cave,\n"
    .string "too?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Losing sucks ass!\n"
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "I came all the way down here to\n"
    .string "impress some chicks.$"

MtMoon_1F_Text_MiriamIntro::
    .string "It's way bigger in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "I lost!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "How do you get out of here?\n"
    .string "Where's David Bowie when you\l"
    .string "need him.$"

MtMoon_1F_Text_JovanIntro::
    .string "AHHH!\n"
    .string "Don't sneak up on me!$"

MtMoon_1F_Text_JovanDefeat:: @ 8172927
    .string "My Pokémon really fizzed out!$"

MtMoon_1F_Text_JovanPostBattle:: @ 817293C
    .string "I have to find stronger Pokémon.\n"
    .string "I'll keep looking?$"

MtMoon_1F_Text_IrisIntro::
    .string "Whadaya want?\n"
    .string "I'm waiting for my friends$"

MtMoon_1F_Text_IrisDefeat::
    .string "Aww... I lost?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "I came because I heard there are\n"
    .string "some very rare fossils here.$"

MtMoon_1F_Text_KentIntro::
    .string "Suspicious men are in the cave.\n"
    .string "What about you?$"

MtMoon_1F_Text_KentDefeat::
    .string "You got me!$"

MtMoon_1F_Text_KentPostBattle::
    .string "The suspicious men? I saw them...\n"
    .string "I'm sure they're from Team Rocket!$"

MtMoon_1F_Text_RobbyIntro::
    .string "You need to go through this cave\n"
    .string "to get to Cerulean City.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Dammit!$"

MtMoon_1F_Text_RobbyPostBattle:: @ 8172A97
    .string "I like Zubat!\n"
    .string "It reminds me of the caves back\l"
    .string "home.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Beware!\n"
    .string "Zubats above!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "I'm excavating for fossils here\n"
    .string "under Mt. Moon.\p"
    .string "Sometimes, Brock lends me a hand.$"
