SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "My daughter is so self-centered.\n"
    .string "She only has a few friends.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "My daughter likes to mimic people.\n"
    .string "It's very annoying.\p"
    .string "Her hobby has earned her the\n"
    .string "nickname Copycat around here.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey:: @ 819AC4B
    .string "Chansey: Chaan! Sii!$"

