PokemonTower_7F_Text_Grunt1Intro::
    .string "What the fuck do you want?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "Grr, I give!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "I'm not going to forget this!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "This old guy marched right up\n"
    .string "here while we're working.\p"
    .string "Then, he starts ranting about how\n"
    .string "Team Rocket's killing Pokémon.\p"
    .string "So, we're just talking it over\n"
    .string "like civilized people.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Please!\n"
    .string "No more!$"

PokemonTower_7F_Text_Grunt2PostBattle:: @ 817A477
    .string "Pokémon are only good for making\n"
    .string "money. Why not use them?\p"
    .string "You stay out of our business!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "You're not saving anyone, kid!$"

PokemonTower_7F_Text_Grunt3Defeat:: @ 817A4EE
    .string "Don't fight us Rockets!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "You're not getting away with this!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe:: @ 817A529
    .string "Mr. Fuji: Heh?\n"
    .string "You came to save me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "Cubone's mother.\p"
    .string "I think Marowak's spirit has\n"
    .string "finally left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, Pokémon\n"
    .string "House, at the foot of this tower.$"

