PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Yes, yes.\n"
    .string "It's ¥50 for a ticket.\p"
    .string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Thank you! Come again!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Right, ¥50!\n"
    .string "Thank you!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "What are you trying to pull?\n"
    .string "You're broke, get out of here!$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Enjoy and don't touch anything.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "Hey! How'd you get back here?\n"
    .string "Whatever, I don''t get paid enough.\p"
    .string "You can chill if you don't mess aroung.\n"
    .string "By the way, Do you know what Amber is?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter:: @ 81905B1
    .string "Amber contains the genetic matter\n"
    .string "of ancient Pokémon.\p"
    .string "It's like that gem from Jurrasic Park\n"
    .string "with the mosquito in it.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap:: @ 8190627
    .string "Amber is fossilized tree sap.\n"
    .string "After eons it becomes a gem.\p"
    .string "Amber can sometimes contain insects\n"
    .string "that have fed from ancient Pokémon.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "Never did I think I would get to\n"
    .string "see the bones of a dragon!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Ssh! Listen, I need to share a\n"
    .string "secret with someone.\p"
    .string "I think that this chunk of Amber\n"
    .string "contains Pokémon DNA!\p"
    .string "It would be a shattering scientific\n"
    .string "breakthrough if Pokémon could be\l"
    .string "resurrected from it.\p"
    .string "But, my colleagues just ignore\n"
    .string "what I have to say.\p"
    .string "So, I have a favor to ask!\p"
    .string "I want you to get this examined at\n"
    .string "a Pokémon Lab somewhere.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan:: @ 8190866
    .string "{PLAYER} received the Old Amber\n"
    .string "from the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Ssh!\n"
    .string "Get the Old Amber checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "We have two fossils of rare,\n"
    .string "prehistoric Pokémon on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "There is a beautiful piece of\n"
    .string "Amber in a clear gold color.$"

PewterCity_Museum_1F_Text_AerodactylFossil:: @ 8190945
    .string "Aerodactyl Fossil\n"
    .string "A primitive and rare Pokémon.$"

PewterCity_Museum_1F_Text_KabutopsFossil:: @ 8190975
    .string "Kabutops Fossil\n"
    .string "A primitive and rare Pokémon.$"

