SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "Dance, dance!\n"
    .string "Chansey Dance!\p"
    .string "You join in, too!\n"
    .string "Dance, dance!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "Would you like to dance?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "Come on, dance!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance:: @ 81A4DD8
    .string "{PLAYER} danced the Chansey Dance!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "Ahahahaha!\p"
    .string "There, you're all chipper now!\n"
    .string "Lucky!$"

SevenIsland_SevaultCanyon_House_Text_Chansey:: @ 81A4E26
    .string "Chansey: Chansi! Chansi!$"
