VermilionCity_House3_Text_PidgeyFlyLetterToSaffron:: @ 81953AF
    .string "I'm sending my Pidgey up north\n"
    .string "with a letter to Saffron.$"

VermilionCity_House3_Text_Pidgey:: @ 81953EE
    .string "Pidgey: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter:: @ 8195400
    .string "Dear Vanessa,\n"
    .string "I miss you boo.\p"
    .string "I heard Saffron is having issues\n"
    .string "with Team Rocket.\p"
    .string "Vermilion appears to be safe\n"
    .string "for now. Talk to you soon.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom:: @ 8195471
    .string "I want to exchange Mail with all\n"
    .string "sorts of people.$"

