Text_SeismicTossTeach::
    .string "The secrets of space…\n"
    .string "The mysteries of earth…\p"
    .string "There are so many things\n"
    .string "which we know little about.\p"
    .string "But that should push us toward\n"
    .string "advancement, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about Seismic Toss?\n"
    .string "Should I teach that to a Pokémon?$"

Text_SeismicTossDeclined::
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon:: @ 8190AD5
    .string "Which Pokémon wants to learn\n"
    .string "Seismic Toss?$"

Text_SeismicTossTaught::
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone:: @ 8190B30
    .string "Moon Stone, huh?\p"
    .string "What's so special about it?\n"
    .string "Looks like an ordinary rock to me.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "July 20, 1969!\p"
    .string "Mankind first set foot on the\n"
    .string "moon! Amazing to witness!\p"
    .string "I bought a color TV just so I\n"
    .string "could watch that news.\p"
    .string "One small step for man,\n"
    .string "One giant leap for mankind$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "This month, we're running a space\n"
    .string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu:: @ 8190C1E
    .string "I want a Pikachu!\n"
    .string "It's so cute!\p"
    .string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise:: @ 8190C60
    .string "Yeah, a Pikachu soon, I promise!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Space Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon:: @ 8190C8F
    .string "A meteorite that fell from Mt. Moon.\n"
    .string "It is thought to be a Moon Stone.$"

