Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests:: @ 819D85C
    .string "There are Pokémon that only live\n"
    .string "in forests and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to catch 'em all.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "I'm sure you already know that the\n"
    .string "small trees can be cut, right?\p"
    .string "If you don't, I can't help you\n"
    .string "because I'm just an NPC.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "I'm sure you know that pressing the\n"
    .string "B button will cancel an evolution?\p"
    .string "Some Pokémon can only learn moves\n"
    .string "During an earlier stage.\p"
    .string "There is also an item to stop\n"
    .string "your Pokémon from Evololving.$"

