Route20_Text_BarryIntro::
    .string "The water is shallow here.\n"
    .string "There are many people swimming.$"

Route20_Text_BarryDefeat::
    .string "Splash!$"

Route20_Text_BarryPostBattle:: @ 8187E83
    .string "I wish I could ride my Pokémon.\n"
    .string "I bet you're not tired.$"

Route20_Text_ShirleyIntro:: @ 8187EBB
    .string "Seafoam is a quiet getaway.\n"
    .string "I'm vacationing here.$"

Route20_Text_ShirleyDefeat::
    .string "Quit it!$"

Route20_Text_ShirleyPostBattle::
    .string "There's a huge cavern underneath\n"
    .string "this island.$"

Route20_Text_TiffanyIntro::
    .string "I love floating with the fishes\n"
    .string "here among the waves.$"

Route20_Text_TiffanyDefeat::
    .string "Yowch!$"

Route20_Text_TiffanyPostBattle::
    .string "Want to float with me?$"

Route20_Text_IreneIntro::
    .string "Are you on vacation, too?$"

Route20_Text_IreneDefeat::
    .string "No mercy at all!$"

Route20_Text_IrenePostBattle:: @ 8187FA3
    .string "Seafoam used to be a single island\n"
    .string "in the distant past.$"

Route20_Text_DeanIntro::
    .string "Check out my buff physique!$"

Route20_Text_DeanDefeat::
    .string "Wimpy!$"

Route20_Text_DeanPostBattle::
    .string "I should've been buffing up my\n"
    .string "Pokémon, not me!$"

Route20_Text_DarrinIntro:: @ 818802E
    .string "Why are you riding a Pokémon?\n"
    .string "Can't you swim?$"

Route20_Text_DarrinDefeat::
    .string "Ouch!\n"
    .string "Torpedoed!$"

Route20_Text_DarrinPostBattle:: @ 818806D
    .string "Riding a Pokémon sure looks fun!$"

Route20_Text_RogerIntro:: @ 818808E
    .string "I rode my bird Pokémon here.$"

Route20_Text_RogerDefeat::
    .string "Oh, no!\n"
    .string "Now what am I to do?$"

Route20_Text_RogerPostBattle::
    .string "My birds are exhausted.\n"
    .string "They can't Fly me back!$"

Route20_Text_NoraIntro::
    .string "My boyfriend gave me big pearls.$"

Route20_Text_NoraDefeat::
    .string "Oh, no!\n"
    .string "My pearls were in them!$"

Route20_Text_NoraPostBattle::
    .string "Will my pearls grow bigger inside\n"
    .string "Cloyster?$"

Route20_Text_MissyIntro:: @ 8188165
    .string "I swam here from Cinnabar Island.\n"
    .string "It wasn't easy, I tell you.$"

Route20_Text_MissyDefeat::
    .string "I'm so disappointed!$"

Route20_Text_MissyPostBattle:: @ 81881B8
    .string "Pokémon have taken over an\n"
    .string "abandoned mansion on Cinnabar.\p"
    .string "They call it the Pokémon Mansion\n"
    .string "now.$"

Route20_Text_MelissaIntro:: @ 8188218
    .string "Cinnabar, in the west, has a LAB\n"
    .string "for Pokémon.\p"
    .string "My daddy works there.$"

Route20_Text_MelissaDefeat::
    .string "Wait!\n"
    .string "You're supposed to wait!$"

Route20_Text_MelissaPostBattle:: @ 818827B
    .string "Cinnabar is a volcanic island.\p"
    .string "I heard it rose out of the sea\n"
    .string "when a volcano erupted.$"

Route20_Text_SeafoamIslands:: @ 81882D1
    .string "Seafoam Islands$"

Route20_Text_MistyTrainsHere:: @ 81882E1
    .string "Strong Trainers and Water Pokémon\n"
    .string "are common sights in these parts.\p"
    .string "They say that Misty of the\n"
    .string "Cerulean Gym trains here.$"
