SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "You, mon petit!\n"
    .string "We are busy here!\l"
    .string "Out of ze way!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash:: @ 8173429
    .string "I saw an odd Berry in the trash.\n"
    .string "I wonder what that was?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "I'm so busy I'm getting dizzy!\n"
    .string "You have to give me room here!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Po-ta-toes!\p"
    .string "Boil 'em, mash 'em, stick em in\n"
    .string "a stew!$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton:: @ 81734D3
    .string "Did you hear about Snorlax?\n"
    .string "It's a glutton.\p"
    .string "No other Pokémon eats and sleeps\n"
    .string "the way Snorlax can and does!\p"
    .string "Reminds me of my ex-girlfriend!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Whimper… Sniff…\p"
    .string "I only get to peel onions…\n"
    .string "My eyes burn…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "Er-hem!\n"
    .string "Indeed I am le Chef!\p"
    .string "Le main course is$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Salmon du Salad!\p"
    .string "Les guests may gripe it's fish\n"
    .string "again, however!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Eels au Barbecue!\p"
    .string "Les guests will mutiny, I fear.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Prime Beefsteak!\p"
    .string "But, have I enough fillets du\n"
    .string "beef?$"

