VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish:: @ 8193EC1
    .string "Welcome, I am the Fishing Guru.\p"
    .string "I am absolutely infatuated with\n"
    .string "fishing on the open sea.\p"
    .string "Tell me, do you partake?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Splendid! I like your style.\n"
    .string "I beleive we are now acquanted.\p"
    .string "I bequeath you this gift.!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru:: @ 8193F81
    .string "{PLAYER} received an Old Rod from\n"
    .string "the Fishing Guru.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "To be away from it all and be\n"
    .string "one with nature. Magnificent.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "This is quite a dissapointment.$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Good day, {PLAYER}!\p"
    .string "How might the fishing be?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "How unfortunate!\p"
    .string "I had a gift to give you,\n"
    .string "however you have no room for it!$"

