Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou:: @ 819D9D4
    .string "Okay, set six Poké Balls in my\n"
    .string "belt…\p"
    .string "Now I'm looking like a pro\n"
    .string "Pokémon Trainer.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean:: @ 819DA3A
    .string "Team Rocket attacks Cerulean\n"
    .string "citizens…\p"
    .string "Not a day goes by without Team\n"
    .string "Rocket being in the news.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500:: @ 819DA9A
    .string "Man: Hello there, young man!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret Pokémon\n"
    .string "- a Magikarp - for just ¥500!\p"
    .string "I know you're gonna buy it, right?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500:: @ 819DB34
    .string "Man: Hello there, little lady!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret Pokémon\n"
    .string "- a Magikarp - for just ¥500!\p"
    .string "I know you're gonna buy it, right?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} paid a fair ¥500\n"
    .string "and bought the Magikarp…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "No? You said no? I'm only doing\n"
    .string "this as a favor to you!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "There's no more room for any more\n"
    .string "Pokémon, it looks like.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "You can't con a conman!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds:: @ 819DC9A
    .string "Man: Well, I don't give refunds.\n"
    .string "You knew what you were getting!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "Sometimes, you'll have too many\n"
    .string "Pokémon with you to add any more.\p"
    .string "In that case, you should just\n"
    .string "store some using any PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "It's a newspaper. It reads:\p"
    .string "Team Rocket continues to\n"
    .string "rampage through Kanto!$"

