PalletTown_RivalsHouse_Text_HiBrothersAtLab:: @ 818D58C
    .string "Daisy: Hi, {PLAYER}!\p"
    .string "{RIVAL}, is at gramps lab$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival:: @ 818D5C4
    .string "Daisy: {PLAYER}, I heard you\n"
    .string "battled against {RIVAL}.\p"
    .string "I wish I was there!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Gramps asked you to run an\n"
    .string "errand?\p"
    .string "That's lazy of him.\n"
    .string "Here, this will help you.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy:: @ 818D661
    .string "{PLAYER} received a Town Map\n"
    .string "from Daisy.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "You don't have space for this in\n"
    .string "your Bag.$"

PalletTown_RivalsHouse_Text_ExplainTownMap:: @ 818D6AF
    .string "You can use the Town Map to find\n"
    .string "out where you are, or check the\l"
    .string "names of places.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest:: @ 818D701
    .string "Daisy: Just like people, Pokémon\n"
    .string "are living things.\p"
    .string "When they get tired, please give\n"
    .string "them a rest.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto:: @ 818D763
    .string "It's a big map of the Kanto region.\n"
    .string "Now this would be useful!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "The shelves are crammed full of\n"
    .string "Pokémon novels. Wait...\p"
    .string "There's a book hidden back here\n"
    .string "Looks like a romance book.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon:: @ 818D7D3
    .string "Daisy: Hi, {PLAYER}!\n"
    .string "Good timing.\p"
    .string "I'm about to have some tea.\n"
    .string "Would you like to join me?\p"
    .string "Oh, but look.\n"
    .string "Your Pokémon are a little dirty.\p"
    .string "Would you like me to groom one?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "You don't need any grooming done?\n"
    .string "Okay, we'll just have tea.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Which one should I groom?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime:: @ 818D8CC
    .string "Daisy: Okay, I'll get them\n"
    .string "looking nice in no time.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
    .string "{FONT_2}{STR_VAR_1} looks dreamily content…\p"
    .string "{FONT_5}DAISY: There you go! All done.\n"
    .string "See? Don't they look cute?!\p"
    .string "hehehe…\n"
    .string "They're such an adorable Pokémon.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Um...That's an egg...$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon:: @ 818D9A5
    .string "Daisy: Your Pokémon grow to love\n"
    .string "you if you raise them right.\p"
    .string "For example, {PLAYER}, may I see\n"
    .string "your first Pokémon?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "They couldn't possibly love you\n"
    .string "any more than they does now.\p"
    .string "Your Pokémon is happy beyond\n"
    .string "words.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "They looks very happy.\p"
    .string "I wish {RIVAL} could see this and\n"
    .string "learn something from you.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "They're friendly with you.\n"
    .string "Keep being good to them!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "They're warming up to you.\n"
    .string "I think they are starting to like you.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "They're not quite familiar with\n"
    .string "you yet.\p"
    .string "Pokémon are all quite shy when\n"
    .string "you first get them.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, I don't like the way\n"
    .string "they glare at you.\p"
    .string "Could you try being a little nicer\n"
    .string "to them?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Um, it's not easy for me to say\n"
    .string "this, but…\p"
    .string "Is there some reason why your\n"
    .string "Pokémon would hate you so much?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“The lovely and sweet\n"
    .string "Clefairy”$"

