SSAnne_2F_Room4_Text_LamarIntro::
    .string "Which do you go for more,\n"
    .string "a strong or a rare Pokémon?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "I salute you!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Personally, I prefer strong and\n"
    .string "rare Pokémon. Double whammy!$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "I don't believe I saw you at the\n"
    .string "party?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Take it easy!$"

SSAnne_2F_Room4_Text_DawnPostBattle:: @ 8173FB9
    .string "Oh, I adore your strong Pokémon!\n"
    .string "Oh, how I envy you for them!$"

