CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel:: @ 81955C7
    .string "Super Repel keeps weaker Pokémon\n"
    .string "at a distance…\p"
    .string "It's a more powerful Repel.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "You should always be prepared\n"
    .string "with a Revive in your bag.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign:: @ 8195638
    .string "Top-Shelf Items for Trainers!\p"
    .string "2F: Trainer's Market$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes:: @ 819566B
    .string "We have a customer, Lance, who\n"
    .string "is always in here.\p"
    .string "He always buys capes.\p"
    .string "Who in the world needs that\n"
    .string "many capes?\p"
    .string "I've never even worn one!$"
