SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Grunt!\p"
    .string "I am the Karate Master!\n"
    .string "I am the Leader here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Waaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Hwa!\n"
    .string "Arrgh! Beaten!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Indeed, I have lost!\p"
    .string "But, I beseech you, do not take\n"
    .string "our emblem as your trophy!\p"
    .string "In return, I will give you prized\n"
    .string "Fighting Pokémon!\p"
    .string "Take both if you please!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "Grunt!\n"
    .string "Stay and train at karate with us!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Hey!\n"
    .string "Take your shoes off!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "I concede!$"

SaffronCity_Dojo_Text_MikePostBattle:: @ 819B29D
    .string "I respect your strength!\n"
    .string "Please share your power with us!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "I hear you're good!\n"
    .string "Show me!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "Point {PLAYER}!\n"
    .string "You win!$"

SaffronCity_Dojo_Text_HidekiPostBattle:: @ 819B30F
    .string "Our Master is a pro fighter.\n"
    .string "He's one many tournements!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "Hiyah!\n"
    .string "I have no fear!\p"
    .string "I shatter boulders for training\n"
    .string "every day!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "Oof!\n"
    .string "I jammed my fingers!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "The only thing that can take us\n"
    .string "down is psychic power.\p"
    .string "This is why Sabrina is Gym leader\n"
    .string "in Saffron.$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "Hwaah!\p"
    .string "You are my opponent?\n"
    .string "Pathetic!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "Ugh!\n"
    .string "I tap out!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "Prime fighters from around\n"
    .string "the world train here.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "You want the hard-kicking\n"
    .string "Hitmonlee?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the Karate Master.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "You want the fast-punching\n"
    .string "Hitmonchan?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Better not get greedy…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "Enemies on every side!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "What goes around comes around.$"

SaffronCity_Dojo_Text_FightingDojo:: @ 819B52E
    .string "Fighting Dojo$"

