PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "I totally got scammed! Ugh!\n"
    .string "I was tricked into buying a Pokémon!\p"
    .string "It's a fish Pokémon and it is\n"
    .string "totally weak and it cost ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "My brother sent me in here looking\n"
    .string "for headlight fluid.\p"
    .string "Every store I go to they just\n"
    .string "laugh at me.$"

