RocketHideout_B1F_Text_Grunt1Intro::
    .string "Who the fuck are you?\n"
    .string "How did you get here?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Shit!\n"
    .string "Beat my ass!$"

RocketHideout_B1F_Text_Grunt1PostBattle:: @ 8174EFA
    .string "Sonuvabitch!$"

RocketHideout_B1F_Text_Grunt2Intro:: @ 8174F2C
    .string "HEY! We are the ones who are\n"
    .string "supposed to break and enter!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Holy shit!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "You're not going to get away with\n"
    .string "this, you fucking brat!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Come on! I am on my break...$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "Whatever, kid!$"

RocketHideout_B1F_Text_Grunt3PostBattle:: @ 8174FB3
    .string "This is the second time!\n"
    .string "Get out of my face!$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "What the fuck you doing here?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "Fuck outta here!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "I don't get paid for this shit…\n"
    .string "Take the elevator to see the Boss.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Are you lost, where's your mommy?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "How the fuck…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Fuck this! I opened the door.\n"
    .string "Do what you want, spoiled brat!$"

RocketHideout_B1F_Text_Meowth::
    .string "I don't feel like fighting today\n"
    .string "I'm still sore from Mt. Moon.$"

