RocketHideout_B4F_Text_GiovanniIntro::
    .string "Hm, I must say, I am impressed.\n"
    .string "Your brutality is to be commended.\p"
    .string "Team Rocket captures Pokémon from\n"
    .string "around the world for our cause.\p"
    .string "They're tools for keeping\n"
    .string "our income coming in.\p"
    .string "My name is, Giovanni!\p"
    .string "You've beaten all of my subordinates.\n"
    .string "Let's see how you fair against a Pro!$"

RocketHideout_B4F_Text_GiovanniDefeat:: @ 8175318
    .string "Color me impressed...$"

RocketHideout_B4F_Text_GiovanniPostBattle:: @ 817532D
    .string "I see that you raise Pokémon\n"
    .string "with care and attention.\p"
    .string "You remind me of my self as a\n"
    .string "blooming trainer all those years ago.\p"
    .string "You won the Scope fair and square.\p"
    .string "I hope we meet again…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "I know you!\n"
    .string "You were at Mt. Moon!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Not again!$"

RocketHideout_B4F_Text_Grunt2PostBattle:: @ 817540C
    .string "What's your beef against Team\n"
    .string "Rocket, anyway?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "How can you not see that this is\n"
    .string "a means to an end?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ugh$"

RocketHideout_B4F_Text_Grunt3PostBattle:: @ 817546A
    .string "Boss!\n"
    .string "Please don't demote me again!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "Oh no! You again? But I'm alone!\n"
    .string "You can't have my Lift Key!$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "Jessie is going to hang me\n"
    .string "out to dry!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "My Lift Key!\n"
    .string "I dropped it during the battle!$"

