CeruleanCity_House2_Text_RocketsStoleTMForDig:: @ 8191E13
    .string "Those dang Rockets!\p"
    .string "Look what they done to my house\p"
    .string "They stole my TM for teaching\n"
    .string "Pokémon how to Dig!\p"
    .string "I was going to use it on a\n"
    .string "Mankey or a Sandshrew…\p"
    .string "That cost me a bundle, it did!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "Eh, you keep it.\p"
    .string "I decided to teach Diglett how to\n"
    .string "Dig without a TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood:: @ 8191F2A
    .string "Team Rocket must be trying to Dig\n"
    .string "their way into no good!\p"
    .string "But they will only dig thier\n"
    .string "own grave.$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut:: @ 8191F64
    .string "Team Rocket blasted through!\n"
    .string "my back wall! Sons of bitchs!$"

