LavenderTown_House1_Text_Cubone:: @ 819396B
    .string "Cubone: boooone. Cuboooone.$"

LavenderTown_House1_Text_RocketsKilledCubonesMother:: @ 819397D
    .string "Those horrible Rockets!\n"
    .string "They deserve no mercy!\p"
    .string "That poor Cubone's mother…\p"
    .string "It was killed trying to escape from\n"
    .string "Team Rocket.\p"
    .string "He's been crying ever since.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone:: @ 81939F8
    .string "The ghost of Pokémon Tower is\n"
    .string "gone!\p"
    .string "Someone must have put the\n"
    .string "spirit to rest!$"

