VermilionCity_Text_GrimerMultipliesInSludge::
    .string "We are very conscience here about\n"
    .string "trash and waste.\p"
    .string "Grimer multiplies in highly\n"
    .string "polluted areas.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor:: @ 817F776
    .string "Did you see the S.S. Anne?\n"
    .string "She's docked in port?$"

VermilionCity_Text_SSAnneHasDepartedForYear:: @ 817F7A6
    .string "So, the S.S. Anne has departed?\p"
    .string "She'll be back in Vermilion about\n"
    .string "this time next year.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "I'm putting up a building on this\n"
    .string "plot of land.\p"
    .string "Machop is stomping the land\n"
    .string "to lay down the foundation.$"

VermilionCity_Text_Machop:: @ 817F871
    .string "Machop: Chop! MaaaaCHOP!$"

VermilionCity_Text_MachopStompingLandFlat:: @ 817F888
    .string "A Machop is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear:: @ 817F8AC
    .string "The S.S. Anne is a cruise ship\n"
    .string "that travels the world.\p"
    .string "It visits Vermilion once a year.$"

VermilionCity_Text_CitySign:: @ 817F8FB
    .string "Vermilion City\n"
    .string "Sunset City$"

VermilionCity_Text_SnorlaxBlockingRoute12:: @ 817F928
    .string "Notice!\p"
    .string "Route 12 may be blocked off by a\n"
    .string "sleeping Snorlax.\p"
    .string "Detour through Rock Tunnel to\n"
    .string "get to Lavender Town.\p"
    .string "Vermilion PD$"

VermilionCity_Text_PokemonFanClubSign:: @ 817F9A1
    .string "The Pokémon Fan Club\n"
    .string "All Pokéfans welcome!$"

VermilionCity_Text_GymSign:: @ 817F9CC
    .string "Vermilion City Pokémon Gym\n"
    .string "Leader: Lt. Surge\l"
    .string "The Lightning Lieutenant!$"

VermilionCity_Text_VermilionHarbor:: @ 817FA11
    .string "Vermilion Harbor$"

VermilionCity_Text_WelcomeToTheSSAnne:: @ 817FA22
    .string "Welcome to the S.S. Anne!$"

VermilionCity_Text_DoYouHaveATicket:: @ 817FA3C
    .string "Welcome to the S.S. Anne!\p"
    .string "Ticket, please?$"

VermilionCity_Text_FlashedSSTicket:: @ 817FA77
    .string "{FONT_2}{PLAYER} flashed the S.S. Ticket!\p"
    .string "{FONT_4}Great!\n"
    .string "Welcome to the S.S. Anne!$"

VermilionCity_Text_DontHaveNeededSSTicket:: @ 817FABA
    .string "{FONT_2}{PLAYER} doesn't have the needed\n"
    .string "S.S. Ticket.\p"
    .string "{FONT_4}Sorry!\p"
    .string "You need a ticket for the party.$"

VermilionCity_Text_TheShipSetSail::
    .string "The S.S. Anne set sail.$"

VermilionCity_Text_BoardSeagallopTriPass:: @ 817FB23
    .string "Ah, you have a Tri-Pass.\p"
    .string "Would you like to board\n"
    .string "a Seagallop ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "Seagallop Hi-Speed 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass:: @ 817FBB8
    .string "Ah, you have a Rainbow Pass.\p"
    .string "Would you like to board\n"
    .string "a Seagallop ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock:: @ 817FC00
    .string "Oh! That's a MysticTicket!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "Navel Rock anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland:: @ 817FC5F
    .string "Oh! That's an AuroraTicket!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "Birth Island anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a Seagallop ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "Seagallop Hi-Speed 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "Seagallop Hi-Speed 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of Prof. Oak's Aides.\p"
    .string "Did you meet the other Aide?\p"
    .string "He had a package from Prof. Oak\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "Route 2, {PLAYER}.\p"
    .string "If you're in the Route 2 area,\n"
    .string "please look for him.$"

