PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow:: @ 81917E4
    .string "Pokémon are eager to learn new moves\n"
    .string "from experience and from people.\p"
    .string "They are amazing and can adapt\n"
    .string "almost as quick as people.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused:: @ 8191840
    .string "A Pokémon becomes easier to \n"
    .string "catch if it has a status effect.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "But if you didn't know that then\l"
    .string "why are you out here?$"

