CeladonCity_Gym_Text_ErikaIntro::
    .string "Oh, hello…\n"
    .string "Lovely weather today, isn't it?\l"
    .string "It's so pleasant…\p"
    .string "……\n"
    .string "Oh, I must have dozed off.\p"
    .string "My name is Erika.\n"
    .string "I am the Leader of Celadon Gym.\p"
    .string "I am a master of the art of\n"
    .string "flower arranging.\p"
    .string "My Pokémon are solely of the\n"
    .string "Grass type.\p"
    .string "…Oh, I'm sorry, I had no idea that\n"
    .string "you wished to battle.\p"
    .string "Very well, I'll not go easy on you.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Oh!\n"
    .string "I concede.\l"
    .string "You are remarkably strong.\p"
    .string "I must confer on to you the\n"
    .string "RainbowBadge.$"

CeladonCity_Gym_Text_ErikaPostBattle:: @ 81972B8
    .string "You are cataloging Pokémon?\n"
    .string "I must say I'm impressed.\p"
    .string "Collecting Pokémon seems tedious.\n"
    .string "I quite enjoy my roots.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis:: @ 8197327
    .string "The RainbowBadge will make\n"
    .string "Pokémon up to Lv. 50 obey.\p"
    .string "It also allows Pokémon to use\n"
    .string "Strength in and out of battle.\p"
    .string "Please also take this with you.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} received TM19\n"
    .string "from Erika.$"

CeladonCity_Gym_Text_ExplainTM19:: @ 81973D7
    .string "TM19 contains Giga Drain.\p"
    .string "Half the damage it inflicts is\n"
    .string "drained to heal your Pokémon.$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "You should make room for this.$"

CeladonCity_Gym_Text_KayIntro:: @ 819747C
    .string "I should tell you about this Gym.\p"
    .string "Only ladies are allowed to\n"
    .string "fight here!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "You're too rough!\p"
    .string "I like it to be gentle$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "I'm exhausted now!\n"
    .string "Take it easy on me next time!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Yawn, finnaly.\n"
    .string "I was getting bored.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "My makeup!$"

CeladonCity_Gym_Text_BridgetPostBattle:: @ 8197527
    .string "Now I have to redo my wingtips!$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Oh ho, were you checking me\n"
    .string "out earlier?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "You won! How about we go out?$"

CeladonCity_Gym_Text_TinaPostBattle:: @ 81975D1
    .string "Oh, you were looking at Erika…\n"
    .string "You weren't looking at me…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "What do we have here?\n"
    .string "A fresh new face.\p"
    .string "I'm gonna vine whip that ass!$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Oh, you can give it as good\n"
    .string "as you can take it!$"

CeladonCity_Gym_Text_TamiaPostBattle:: @ 8197664
    .string "You're nice and thorny,\n"
    .string "just like I like 'em!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Hey!\p"
    .string "We don't like fire type\n"
    .string "Pokémon in here!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Oh!\n"
    .string "Now I'm all hot and bothered!$"

CeladonCity_Gym_Text_LisaPostBattle:: @ 8197708
    .string "Our Leader Erika might be quiet,\n"
    .string "but she knows her way around\l"
    .string "people like you.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Such a pleasure to meet you.\n"
    .string "My hobby is Pokémon training.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Oh!\n"
    .string "I'm all flustered now!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "I have a blind date coming up.\n"
    .string "I'll be thinking of you while\l"
    .string "I am with them.$"

CeladonCity_Gym_Text_MaryIntro:: @ 81977E5
    .string "Welcome to Celadon Gym!\p"
    .string "You'd better not underestimate\n"
    .string "the nice ladies here.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Mmmm!\n"
    .string "I can't take much more!$"

CeladonCity_Gym_Text_MaryPostBattle:: @ 819783E
    .string "You brought me to my knees.\n"
    .string "Usually I'm the top!$"

CeladonCity_Gym_Text_GymStatue:: @ 8197874
    .string "Celadon Pokémon Gym\n"
    .string "Leader: Erika\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon:: @ 81978AB
    .string "Celadon Pokémon Gym\n"
    .string "Leader: Erika\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}, {PLAYER}$"

