CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "Ugh, I'm thirsty!\n"
    .string "I want something to drink!\p"
    .string "{FONT_2}Give her a drink?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "Give her which drink?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "OMG TYSM!\p"
    .string "Water!\p"
    .string "Thanks!\n"
    .string "You can have this!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} received a {STR_VAR_2}\n"
    .string "from the little girl.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16:: @ 8195DD4
    .string "TM16 contains Light Screen.\p"
    .string "It's a move that weakens the power\n"
    .string "of special attacks by your foe.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "You're so clutch!\p"
    .string "I love soda!\p"
    .string "Thanks!\n"
    .string "You can have this!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20:: @ 8195E68
    .string "TM20 contains Safeguard.\p"
    .string "It's a move that prevents status\n"
    .string "problems among your Pokémon.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "You are a dream come true!\p"
    .string "Lemonade!\p"
    .string "Thanks!\n"
    .string "You can have this!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33:: @ 8195EF4
    .string "TM33 contains Reflect.\p"
    .string "It's a move that weakens the power\n"
    .string "of physical attacks by your foe.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "You don't have space for this!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "No, thanks!\n"
    .string "I'm gucci now!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature:: @ 8195F98
    .string "My sister is a Trainer!\p"
    .string "But, she's so immature, she's\n"
    .string "so damned annoying!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "Ugh! I'm thirsty!\n"
    .string "I want something to drink!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign:: @ 8196017
    .string "Rooftop Square:\n"
    .string "Vending Machines$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "A vending machine!\n"
    .string "What does it have?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "Insufficient Funds!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "A can of {STR_VAR_1} popped out!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "There's no more room for stuff!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "Not thirsty!$"

