CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "Welcome!\p"
    .string "You can exchange your Coins for\n"
    .string "fabulous prizes next door.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins:: @ 8196984
    .string "Welcome to Rocket Casino!\p"
    .string "Do you need some game Coins?\n"
    .string "Would you like to buy some?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "No?\n"
    .string "Please come play sometime!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Oh, I'm sorry.\n"
    .string "You don't have a Coin Case.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "How unfortunate!\n"
    .string "Your Coin Case is full.$"

CeladonCity_GameCorner_Text_CantAffordCoins:: @ 8196A46
    .string "You can't afford the Coins.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Thank you.\n"
    .string "Here are your Coins!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "This place is sus…\p"
    .string "I heard that this place is run,\n"
    .string "get this, by Team Rocket.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "I think these machines have\n"
    .string "different odds.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "Kid, do you want to play?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan:: @ 8196B0D
    .string "{PLAYER} received 10 Coins\n"
    .string "from the man.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins:: @ 8196B30
    .string "You don't need my Coins!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "My gambling addiction is getting.\n"
    .string "out of hand. My wife left me.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "These slot games…\n"
    .string "I can't stop. I need a life.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "Hey!\p"
    .string "You've things to do, champ!\p"
    .string "Celadon Gym's Leader is Erika.\p"
    .string "She is a user of Grass-type\n"
    .string "Pokémon, and is one with nature.\p"
    .string "She might appear chill because of\n"
    .string "her flower arranging…\p"
    .string "But she's not one to be taken\n"
    .string "lightly!$"

CeladonCity_GameCorner_Text_RareMonsForCoins:: @ 8196CA1
    .string "They offer rare Pokémon that can\n"
    .string "be exchanged for your Coins.\p"
    .string "I just can't seem to win!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Big money!? Dammit, again!?\n"
    .string "I'm usually red hot at slots!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "Wassup?\n"
    .string "Want some Coins?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy:: @ 8196D47
    .string "{PLAYER} received 20 Coins\n"
    .string "from the nice guy.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins:: @ 8196D6F
    .string "You're stacked! Give me some!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant:: @ 8196D87
    .string "Damn! I need more Coins for\n"
    .string "Dratini!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "Huh, what? You're distracting me!\n"
    .string "Here, now scram!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan:: @ 8196DF8
    .string "{PLAYER} received 20 Coins\n"
    .string "from the man.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "You've got plenty of your own\n"
    .string "Coins!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "The trick is tap the machine\n"
    .string "before pulling the lever.$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "I'm on duty!\n"
    .string "Scram, kid!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Crapbaskets!$"

CeladonCity_GameCorner_Text_GruntPostBattle:: @ 8196E9B
    .string "The Team Rocket Hideout might\n"
    .string "be comprimised!\p"
    .string "I better tell Boss!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Huh?!\p"
    .string "A switch behind the poster!?\n"
    .string "Let's push it!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired:: @ 8196F0D
    .string "A Coin Case is required…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Uh oh!\n"
    .string "Don't have the Coin Case!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "A slot machine!\n"
    .string "Want to play?$"

CeladonCity_GameCorner_Text_OutOfOrder:: @ 8196F64
    .string "Out Of Order$"

CeladonCity_GameCorner_Text_OutToLunch:: @ 8196F81
    .string "Out To Lunch$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Someone's keys!\n"
    .string "They'll be back.$"

