CinnabarIsland_Text_DoorIsLocked::
    .string "The door is locked…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab:: @ 8180B34
    .string "Gym Leader Blaine is quite the\n"
    .string "weirdo.\p"
    .string "He's lived on the island before\n"
    .string "the lab was even built.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Scientists conducted experiments\n"
    .string "in that burned-out building.\p"
    .string "You know, the one they call the\n"
    .string "Pokémon Mansion.$"

CinnabarIsland_Text_IslandSign:: @ 8180C0D
    .string "Cinnabar Island\n"
    .string "The Fiery Town of Burning Desire$"

CinnabarIsland_Text_PokemonLab:: @ 8180C3E
    .string "Pokémon Lab$"

CinnabarIsland_Text_GymSign:: @ 8180C4A
    .string "Cinnabar Island Pokémon Gym\n"
    .string "Leader: Blaine\l"
    .string "The Hotheaded Gambler!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland:: @ 8180CAA
    .string "It's me, Bill.\n"
    .string "Long time no see!\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about hanging out?\p"
    .string "There's this island in the far\n"
    .string "south called One Island.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "How about it?\n"
    .string "Do you feel like coming with?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "All right, then.\n"
    .string "Let's go!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Aw, man.\p"
    .string "Well, all right.\n"
    .string "The boat hasn't arrived yet anyway.\p"
    .string "I'll be waiting at the Pokécenter.\p"
    .string "Come see me when you're done with\n"
    .string "your business here.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Looks like my pal's boat arrived,\n"
    .string "too.\p"
    .string "He sent it specially here to\n"
    .string "Cinnabar to pick me up.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, wasn't that a long cruise?\p"
    .string "My buddy Celio seemed to enjoy\n"
    .string "your company.\p"
    .string "I'm sure he'd welcome you if you\n"
    .string "were to visit him again.\p"
    .string "If you have a Tri-Pass, you can\n"
    .string "always take a ferry there from\l"
    .string "Vermilion Port.\p"
    .string "All right, thanks for your company!$"

