Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Fuck, I'm thirsty, though!\p"
    .string "Oh, hold up, the road's closed.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty:: @ 819E1D1
    .string "Yo, is that Tea…\n"
    .string "It looks so good…$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "No fucking way! Thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to Saffron\l"
    .string "City…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this Tea with the other\n"
    .string "guards!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hey kid, how's it going?$"

