CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons:: @ 8191FFB
    .string "That Bill!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare Pokémon.\p"
    .string "He's not above doing all sorts\n"
    .string "of things.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac:: @ 8192079
    .string "Have you heard about Bill?\p"
    .string "Everyone calls him a Pokémaniac!\p"
    .string "I think people are just jealous of\n"
    .string "Bill, the man is a legend.\p"
    .string "Who wouldn't want to brag about\n"
    .string "their Pokémon?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons:: @ 8192116
    .string "Bill has lots of Pokémon!\n"
    .string "He collects rare ones!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "I swear there were stairs\n"
    .string "somewhere here......$"

