CeruleanCity_House1_Text_BadgesHaveAmazingSecrets:: @ 81918E7
    .string "Only top notch Trainers can\n"
    .string "collect Pokémon Badges.\p"
    .string "I see you have at least one.\p"
    .string "Those Badges have amazing secrets,\n"
    .string "just don't ask me how it works?\p"
    .string "'Cause I have no Idea...$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the eight Badges should\n"
    .string "I devulge the secrets of?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "You're welcomed here anytime.$"

CeruleanCity_House1_Text_AttackStatFlash:: @ 81919BE
    .string "The Attack stat of all your\n"
    .string "Pokémon increases a bit.\p"
    .string "It also lets you use the move\n"
    .string "Flash outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut:: @ 8191A31
    .string "Pokémon up to Lv. 30 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "Pokémon of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "Cut outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly:: @ 8191AF9
    .string "The Speed stat of all your\n"
    .string "Pokémon increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "Fly outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength:: @ 8191B69
    .string "Pokémon up to Lv. 50 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "Pokémon of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "Strength outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf:: @ 8191C36
    .string "The Defense stat of all your\n"
    .string "Pokémon increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "Surf outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash:: @ 8191CA9
    .string "Pokémon up to Lv. 70 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "Pokémon of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "Rock Smash outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall:: @ 8191D78
    .string "The Sp. Atk and Sp. Def stats of\n"
    .string "all your Pokémon rise a little bit.\p"
    .string "It also lets you use the move\n"
    .string "Waterfall outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou:: @ 8191DF8
    .string "All Pokémon will obey you!$"

