ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner. Its a public PC.\p"
    .string "The Nurse Joy told me it was ok.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown:: @ 81903E5
    .string "There's a Pokémon Center in every\n"
    .string "town ahead. They charge no money!\p"
    .string "Don't you love free heathcare? Do\n"
    .string "not be shy about healing Pokémon.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons:: @ 8190450
    .string "Pokémon Centers heal your tired,\n"
    .string "hurt, or fainted Pokémon.\p"
    .string "They make your Pokémon completely\n"
    .string "healthy. Makes life easier.$"

