Route3_Text_TunnelFromCeruleanTiring::
    .string "Aw man, I gotta catch my breath…\n"
    .string "Ugh…\p"
    .string "That tunnel from Cerulean takes a\n"
    .string "toll on you!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "You beat my boys in Viridian Forest!\l"
    .string "Time to return the favor!$"

Route3_Text_ColtonDefeat::
    .string "I can see why they lost!$"

Route3_Text_ColtonPostBattle:: @ 818351C
    .string "Me and the boys are gonna go train\n"
    .string "while watching Rocky for inspiration.$"

Route3_Text_BenIntro::
    .string "Sup!\n"
    .string "You got a problem with my shorts?\p"
    .string "Oh? You wanna battle!\n"
    .string "Let's do this!$"

Route3_Text_BenDefeat::
    .string "Wow, you're tough!$"

Route3_Text_BenPostBattle:: @ 81835B4
    .string "I don't know. I like my shorts.\n"
    .string "I'm not sure about branching out.\p"
    .string "Jeans? Dickies? Cargo?\n"
    .string "So many pants!$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You're quite good looking!$"

Route3_Text_JaniceDefeat::
    .string "Don't be so mean!$"

Route3_Text_JanicePostBattle::
    .string "Can I like, get your number?\n"
    .string "Ok, hopefully I'll see you around.$"

Route3_Text_GregIntro:: @ 8183682
    .string "You're a Trainer!\n"
    .string "Let's do it!$"

Route3_Text_GregDefeat:: @ 81836B3
    .string "I need new Pokémon, pronto!$"

Route3_Text_GregPostBattle:: @ 81836D9
    .string "I gotta go buy Poké Balls\n"
    .string "I need a whole new team!$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "Are you coming on to me?$"

Route3_Text_SallyDefeat::
    .string "I like it rough!$"

Route3_Text_SallyPostBattle::
    .string "You're so cute!\n"
    .string "Let me have a bite!$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "Straight to jail!$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "Everyone is entitled to thier pants\n"
    .string "opinion. Just let me have mine.$"

Route3_Text_JamesIntro:: @ 8183807
    .string "I'll battle you with the Pokémon\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Oof. Ya got me!$"

Route3_Text_JamesPostBattle:: @ 8183849
    .string "I guess I have to catch stronger\n"
    .string "Pokémon.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it?$"

Route3_Text_RobinPostBattle:: @ 818389C
    .string "Try not to bump into me again.$"

Route3_Text_RouteSign:: @ 81838C0
    .string "Route 3\n"
    .string "Mt. Moon Ahead$"

