ViridianForest_Text_FriendsItchingToBattle::
    .string "Me and the boys came out to\n"
    .string "catch us some Bug Pokémon!\p"
    .string "They wild out here, they will\n"
    .string "100% fight you. I warned you.$"

ViridianForest_Text_RickIntro:: @ 81722C7
    .string "Hey! You have Pokémon!\n"
    .string "Haha, you're going down!\l"
    .string "Get ready for a beating!$"

ViridianForest_Text_RickDefeat:: @ 81722F9
    .string "Shit!\nCaterpie sucks ass!$"

ViridianForest_Text_RickPostBattle::
    .string "Bugger off! I'll get you back\n"
    .string "another time, mark my words!$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "You came to the wrong neck of the\l"
    .string "woods..forest..YOU KNOW WHAT I MEAN!$"

ViridianForest_Text_DougDefeat::
    .string "Gods Dammit!?\n"
    .string "Useless ass Pokémon!$"

ViridianForest_Text_DougPostBattle::
    .string "You're an ass! I'm going to\n"
    .string "come back stronger!$"

ViridianForest_Text_SammyIntro::
    .string "Where you think you going?!\n"
    .string "Come catch these hands!$"

ViridianForest_Text_SammyDefeat::
    .string "I give up!\n"
    .string "You're bas ass, I guess!$"

ViridianForest_Text_SammyPostBattle::
    .string "You're getting on my nerves.\n"
    .string "You better get out of my face.\p"
    .string "I dropped something and I'm\n"
    .string "looking for it. Get lost!$"

ViridianForest_Text_AnthonyIntro::
    .string "WHO YOU CALLING SMALL!\n"
    .string "I'M WAITING ON A GROWTH SPURT!$"

ViridianForest_Text_AnthonyDefeat::
    .string "UGH!\n"
    .string "I STILL WON'T MY DRINK MILK!$"

ViridianForest_Text_AnthonyPostBattle::
    .string "IM NOT THAT SMALL!$"

ViridianForest_Text_CharlieIntro:: @ 81724F9
    .string "I got a trick up my sleeve!$"

ViridianForest_Text_CharlieDefeat::
    .string "Fuck!\n"
    .string "I just had sand in my eye!$"

ViridianForest_Text_CharliePostBattle:: @ 8172527
    .string "What you standing around for?\n"
    .string "Get out of here!$"

ViridianForest_Text_RanOutOfPokeBalls:: @ 8172559
    .string "Leave me be...$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak:: @ 81725C7
    .string "Trainer Tips\p"
    .string "Make sure you go out and touch\n"
    .string "some real grass. It'll be good\l"
    .string "for you.$"

ViridianForest_Text_UseAntidoteForPoison:: @ 8172629
    .string "If you don't know how to fix\n"
    .string "poison, why are you here?$"

ViridianForest_Text_ContactOakViaPCToRatePokedex:: @ 817265C
    .string "Trainer Tips\p"
    .string "Just becuase you know what is\n"
    .string "in their pants, doesn't mean\l"
    .string "you know their gender!$"

ViridianForest_Text_CantCatchOwnedMons:: @ 81726A3
    .string "Trainer Tips\p"
    .string "Life is like a box of chocolates\n"
    .string "you'll never know what you\l"
    .string "gonna get. Great movie\l"
    .string "Go watch it!$"

ViridianForest_Text_WeakenMonsBeforeCapture:: @ 817271D
    .string "Trainer Tips\p"
    .string "Spending thousands on Pokémon\n"
    .string "Cards isn't healthy.\p"
    .string "What do I know? I'm just a sign.$"

ViridianForest_Text_LeavingViridianForest:: @ 8172773
    .string "Leaving Viridian Forest\n"
    .string "Pewter City Ahead$"

