MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils:: @ 8172BFB
    .string "Far away, on Cinnabar Island,\n"
    .string "there's a Pokémon Lab.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"

MtMoon_B2F_Text_Grunt1Intro:: @ 8172C5A
    .string "We, Team Rocket, shall find the\n"
    .string "fossils!\p"
    .string "Reviving Pokémon from them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "You made me mad!\n"
    .string "Team Rocket will blacklist you!$"

MtMoon_B2F_Text_Grunt2Intro:: @ 8172CFC
    .string "We, Team Rocket, are Pokémon\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle:: @ 8172E4B
    .string "Pokémon lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil:: @ 8172E77
    .string "Do you want the Dome Fossil?$"

MtMoon_B2F_Text_YouWantHelixFossil:: @ 8172E94
    .string "Do you want the Helix Fossil?$"

MtMoon_B2F_Text_ObtainedHelixFossil:: @ 8172EB2
    .string "Obtained the Helix Fossil!$"

MtMoon_B2F_Text_ObtainedDomeFossil:: @ 8172ECD
    .string "Obtained the Dome Fossil!$"

