Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "Trying to go to the Pokémon League?\n"
	.string "Just forget it.\p"
	.string "You need badges, dontcha know?\n"
	.string "I bet you dont have any, huh?\p"
	.string "The guard won't let you pass\n"
	.string "without 'em.\p"
	.string "By the way, did your Pokémon get\n"
	.string "any stronger? Let's find out.$"

Route22_Text_EarlyRivalDefeat::
	.string "Fuck!\n"
	.string "You got lucky, loser!$"

Route22_Text_EarlyRivalPostBattle:: @ 8188974
	.string "I heard the Pokémon League is\n"
	.string "crawling with tough Trainers.\p"
	.string "I just have to go get all the\n"
	.string "Badges first.\p"
	.string "I'll leave you in the dust.\n"
	.string "later, loser!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: {PLAYER}?\n"
	.string "Surprised to see you made it!\p"
	.string "You think you'll be able to tackle\n"
	.string "The Elite Four? You're crazy!\p"
	.string "Hm? I see you collected all of the\n"
	.string "Badges too. Not bad for a loser.\p"
	.string "You know what, {PLAYER}? I think\n"
	.string "It's time for me to put you in\p"
	.string "the ground! Come on!$"

Route22_Text_LateRivalDefeat::
	.string "Arceus dammit!?\p"
	.string "Now, I have to go to the\n"
	.string "Pokémon Center! Asshole!$"

Route22_Text_LateRivalPostBattle::
	.string "Eat my ass, loser!.\n"
	.string "I'm ready for the Pokémon League!\p"
	.string "{PLAYER}, just go home to mommy.\p"
	.string "But hey, who knows, maybe one!\n"
	.string "day you won't suck!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign:: @ 8188BFF
	.string "Pokémon League\n"
	.string "Front Gate$"

