PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "Whaddya want!?\p"
    .string "Team Rocket is at Mt. Moon?\n"
    .string "That crazy talk! How can that be?\p"
    .string "Why are you trying to talk to me?!\n"
    .string "Can't you see I'm on the phone?\p"
    .string "Beat it!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff:: @ 81916EA
    .string "Jigglypuff: Jigaly puff,\n"
    .string "jigalee ee puff. Jiggalee puff,\l"
    .string "Jigaleeeeeeeeee.$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Yawn!\p"
    .string "When Jigglypuff sings, Pokémon get\n"
    .string "drowsy…\p"
    .string "…Me, too…\n"
    .string "zzzzzzzz…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu:: @ 8191743
    .string "I really want a Pikachu, so I'm\n"
    .string "trading my Clefairy for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid:: @ 8191780
    .string "I'm trading Pokémon with that kid\n"
    .string "there.\p"
    .string "I had two Pikachu, so I figured\n"
    .string "I might as well trade one.$"

