PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "Oh shit...\l"
    .string "Did one of your Pokémon die?\p"
    .string "Oh fuck! You scared me.\p"
    .string "That means we can fight!\n"
    .string "Let's go!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "Motherfuuuuuuck!\n"
    .string "You assbutt!\p"
    .string "I took it easy on you!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle:: @ 8179DD4
    .string "Fine, it was a good fight.\n"
    .string "I just caught a Cubone by the way.\p"
    .string "But I can't find a Marowak.\n"
    .string "I heard Team Rocket killed a bunch\l"
    .string "for thier skulls. Pretty morbid.\p"
    .string "Well, I better get going.\n"
    .string "I've got better things to do,\l"
    .string "unlike you.\p"
    .string "Later fish breath!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Even we could not identify the\n"
    .string "vengeful spirits above.\p"
    .string "We have discouraged visiters\n"
    .string "to go higher than this level.\p"
    .string "Our Channelers have been trying\n"
    .string "to get a hold of the situation\l"
    .string "but to no avail...\p"
    .string "You have been warned...$"

