SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Bonjour!\n"
    .string "I am ze waiter on this ship!\p"
    .string "I will be happy to serve you\n"
    .string "anything you please!\p"
    .string "… … …\n"
    .string "Ah! ze strong silent type!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "The passengers are restless from\n"
    .string "thr long voyage from the last port.\p"
    .string "You might be challenged by the\n"
    .string "more bored ones.$"

