Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Fuck, I'm thirsty, though!\p"
    .string "Oh, hold up, the road's closed.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty:: @ 819E09B
    .string "Yo, is that Tea…\n"
    .string "It looks so good…$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have it?\n"
    .string "No fucking way! Thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Ahhhhhhh…\l"
    .string "You wanna go to Saffron City?\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this Tea with the other\n"
    .string "guards!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "Hey kid, how's it going?$"

