Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Damn, I'm thirsty!\p"
    .string "Wait there, the road is closed.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty:: @ 819E09B
    .string "Huh? You have some tea?\n"
    .string "Oh man! I am dying for some…$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have it?\n"
    .string "You're a lifesaver!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Ahhhhhhh…\l"
    .string "You wanna go to Saffron City?\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this Tea with the other\n"
    .string "guards!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "Hello again.$"

