CeruleanCity_Gym_Text_MistyIntro::
    .string "Oh hi, you're a cute new face!\p"
    .string "Brock said what? Ugh he is so\n"
    .string "annoying. Let's forget about him\p"
    .string "What is your stratagy when you\n"
    .string "catch and train Pokémon?\p"
    .string "My stratagy is an strong offensive\n"
    .string "with Water-type Pokémon!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03:: @ 81922BF
    .string "TM03 teaches Water Pulse.\p"
    .string "Use it on a water Pokémon!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge:: @ 81922F7
    .string "The CascadeBadge makes all\n"
    .string "Pokémon up to Lv. 30 obey.\p"
    .string "You can now use Cut anytime\n"
    .string "anytime, even out of battle.\p"
    .string "You can Cut down small trees to\n"
    .string "open new paths for your adventure.\p"
    .string "And if you see Brock, give him the\n"
    .string "finger for me. Also, here.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM03\n"
    .string "from Misty.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "You're too much for me!\p"
    .string "I have your reward...\p"
    .string "You can have the CascadeBadge.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "Ahahaha? You? I'm more than good\n"
    .string "enough for you, Sweetcheeks!\p"
    .string "Misty won't be pestered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You overpowered me!$"

CeruleanCity_Gym_Text_DianaPostBattle:: @ 81924E4
    .string "You have to put yourself out\n"
    .string "there to see what you are made of.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Be careful!\p"
    .string "You might get wet...\n"
    .string "Let's get to it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "Sunburned!$"

CeruleanCity_Gym_Text_LuisPostBattle:: @ 8192556
    .string "Misty is a Trainer who's going to\n"
    .string "keep improving.\p"
    .string "She won't go down on you...\n"
    .string "To you! TO YOU!!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yer!\n"
    .string "Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The Leader, Misty, is smoking hot\n"
    .string "but uses Water-type Pokémon.\p"
    .string "You can cool her off with your\n"
    .string "Grass-type Pokémon.\p"
    .string "Or bring her down Electric-type\n"
    .string "style and take her to class!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam:: @ 8192688
    .string "You took Misty to pound town!\n"
    .string "I knew you had it in you!\p"
    .string "Kid, we make a damn-good team!$"

CeruleanCity_Gym_Text_GymStatue:: @ 81926E1
    .string "Cerulean Pokémon Gym\n"
    .string "Leader: Misty\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon:: @ 8192719
    .string "Cerulean Pokémon Gym\n"
    .string "Leader: Misty\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}, {PLAYER}$"

