Text_DreamEaterTeach::
    .string "Yawn, oh man, I'm exhausted.\n"
    .string "I must have dozed off.\p"
    .string "I had a nightmare about\n"
    .string "a Drowzee eating my dream.\p"
    .string "And I think I know how it works…\n"
    .string "I learned how to eat dreams…\p"
    .string "Om nom nom! Spooky spooky!\p"
    .string "Let me teach it to a Pokémon so\n"
    .string "I can sleep peacefully!$"

Text_DreamEaterDeclined::
    .string "…zzzzzzz…$"

Text_DreamEaterWhichMon:: @ 817E3F1
    .string "Which Pokémon wants to learn\n"
    .string "Dream Eater?$"

Text_DreamEaterTaught::
    .string "…zzzzzzzz…\n"
    .string "I…am full…of eaten…dreams.$"

PewterCity_Text_ClefairyCameFromMoon:: @ 817E436
    .string "It's said that Clefairy came down\n"
    .string "from the moon. But it's a myth.\p"
    .string "It's one of those old wive's tales\n"
    .string "shared over generations.$"

PewterCity_Text_BrockOnlySeriousTrainerHere:: @ 817E49F
    .string "There aren't many serious Pokémon\n"
    .string "Trainers here. It's whack.\p"
    .string "They're all like Bug Catchers,\n"
    .string "and little forest wannabes.\p"
    .string "But Brock isn't like he is\n"
    .string "pretty tough.$"

PewterCity_Text_DidYouCheckOutMuseum:: @ 817E53E
    .string "Have you checked out the Museum?$"

PewterCity_Text_WerentThoseFossilsAmazing:: @ 817E55C
    .string "Weren't those fossils from Mt. Moon\n"
    .string "dope as hell?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really? If you haven't then\n"
    .string "you 100% have to go!$"

PewterCity_Text_ThisIsTheMuseum:: @ 817E5AC
    .string "This is it, the Museum.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. They have some cool shit!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "I'm sure you know what\l"
    .string "I'm doin out here?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "You're damn right!\n"
    .string "Someone's gotta do it!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut:: @ 817E644
    .string "I'm spraying Repel to keep wild\n"
    .string "Pokémon out of my garden.\l"
    .string "They keep eating my damn tomatoes!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe:: @ 817E67E
    .string "You're a Trainer, right?\p"
    .string "Brock's looking for new\n"
    .string "challengers. Follow me!$"

PewterCity_Text_GoTakeOnBrock::
    .string "If you have the right stuff,\n"
    .string "go take on Brock!$"

PewterCity_Text_TrainerTipsEarningEXP:: @ 817E6F6
    .string "Trainer Tips\p"
    .string "Make sure to to have fun and not\n"
    .string "take things too seriously.\l"
    .string "Life is too short to not have fun.$"

PewterCity_Text_CallPoliceIfInfoOnThieves:: @ 817E748
    .string "Notice!\p"
    .string "Thieves have been stealing Pokémon\n"
    .string "fossils from Mt. Moon.\p"
    .string "Please call the Pewter Police if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience:: @ 817E7C5
    .string "Pewter's Museum Of Natural Science$"

PewterCity_Text_GymSign:: @ 817E7DE
    .string "Pewter City Pokémon Gym\n"
    .string "Leader: Brock\l"
    .string "The Rock-Solid Pokémon Trainer!$"

PewterCity_Text_CitySign:: @ 817E824
    .string "Pewter City\n"
    .string "The Stone Gray City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm Prof. Oak's Aide.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "Running Shoes from the Aide.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "Running Shoes.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Press the B Button to run.\n"
    .string "But only where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "the Lab.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a pair of Running Shoes\n"
    .string "for my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"

