PokemonTower_3F_Text_HopeIntro::
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "I thank you!\n"
    .string "I'm saved!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "I heard the ghosts can be \n"
    .string "identified by the Silph Scope.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Kekeke…\n"
    .string "Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "Hmm?\n"
    .string "What am I doing?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "Sorry!\n"
    .string "I was possessed!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "Be gone!\n"
    .string "Malevolent spirit!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "Oh, I'm sorry!\n"
    .string "I thought you were a demon!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "The others above…\n"
    .string "They must have been possessed.$"

