SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "You look tired.\n"
    .string "You should take a quick nap.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Don't give up!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Thank you so much.$"

SilphCo_9F_Text_Grunt1Intro:: @ 8176BA3
    .string "Your Pokémon seem to adore you,\n"
    .string "kid!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle:: @ 8176BD0
    .string "If I had started as a Trainer at\n"
    .string "your age…$"

SilphCo_9F_Text_EdIntro:: @ 8176BFB
    .string "Your Pokémon have weak points!\n"
    .string "I can nail them!$"

SilphCo_9F_Text_EdDefeat::
    .string "You hammered me!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Exploiting weak spots does work.\n"
    .string "Think about type advantages.$"

SilphCo_9F_Text_Grunt2Intro:: @ 8176C7A
    .string "I am one of the four Rocket\n"
    .string "Brothers!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Warg!\n"
    .string "Brothers, I lost!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "My brothers will avenge me!$"

SilphCo_9F_Text_FloorSign:: @ 8176CD4
    .string "Silph Co. Head Office\n"
    .string "9F$"

