@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Do you think it's hard to come\n"
    .string "up good names for Pokémon?\p"
    .string "Especially if you've caught a\n"
    .string "whole bunch?\p"
    .string "In Lavender Town, there's a man\n"
    .string "who rates Pokémon nicknames.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender:: @ 819E97B
    .string "If you're trying to get to Lavender\n"
    .string "Town, take Rock Tunnel.\p"
    .string "You can get to Rock Tunnel from\n"
    .string "Cerulean City.$"

