Route9_Text_AliciaIntro:: @ 81847B7
    .string "You have Pokémon with you!\n"
    .string "Let's go, sugar!$"

Route9_Text_AliciaDefeat::
    .string "Too sweet…$"

Route9_Text_AliciaPostBattle::
    .string "The tunnel coming up is pitch-black\p"
    .string "You'll need Flash to get through\n"
    .string "there.$"

Route9_Text_ChrisIntro::
    .string "Who's that walking there with those\n"
    .string "good-looking Pokémon?$"

Route9_Text_ChrisDefeat::
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle::
    .string "Keep it walking!$"

Route9_Text_DrewIntro:: @ 818489E
    .string "I'm taking Rock Tunnel to\n"
    .string "Lavender Town…$"

Route9_Text_DrewDefeat::
    .string "Can't measure up…$"

Route9_Text_DrewPostBattle:: @ 81848DE
    .string "Are you off to Rock Tunnel?$"

Route9_Text_CaitlinIntro::
    .string "Don't you dare antagonize me!$"

Route9_Text_CaitlinDefeat::
    .string "No!\n"
    .string "You're too much.$"

Route9_Text_CaitlinPostBattle::
    .string "You're obviously talented.\n"
    .string "Good luck out there!$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored as hell, eh!$"

Route9_Text_JeremyDefeat::
    .string "Keep it coming, eh!\p"
    .string "Oh shit.\n"
    .string "I'm out of Pokémon, eh!$"

Route9_Text_JeremyPostBattle::
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"

Route9_Text_BriceIntro::
    .string "Aw, look at you!\n"
    .string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat::
    .string "What the fuck!?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Kids should be as tough as you!$"

Route9_Text_BrentIntro::
    .string "I got up early every day to raise\n"
    .string "my Pokémon from cocoons!$"

Route9_Text_BrentDefeat:: @ 8184A6A
    .string "What?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
    .string "I have to collect more than bugs\n"
    .string "to get stronger…$"

Route9_Text_AlanIntro::
    .string "YEAH!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat::
    .string "Wowza!\n"
    .string "You beat me fair 'n square!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "I make sure to laugh everyday!$"

Route9_Text_ConnerIntro:: @ 8184B18
    .string "Go, my super Bug Pokémon!$"

Route9_Text_ConnerDefeat::
    .string "My insectoids…$"

Route9_Text_ConnerPostBattle:: @ 8184B3B
    .string "If you don't like Bug Pokémon,\n"
    .string "you bug me!$"

Route9_Text_RouteSign:: @ 8184B66
    .string "Route 9\n"
    .string "Cerulean City - Rock Tunnel$"

