Route24_Text_JustEarnedFabulousPrize::
    .string "Congratulations! You beat our\n"
    .string "five Trainers!\p"
    .string "You just earned a fabulous prize!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer:: @ 8188C93
    .string "{PLAYER} received a Nugget\n"
    .string "from the mystery Trainer!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "You don't have any room!$"

Route24_Text_JoinTeamRocket::
    .string "This was a test and you passed\n"
    .string "with flying colors!!!\p"
    .string "You have earned an opportunity\n"
    .string "to join.....Team Rocket!\p"
    .string "We are an organization that\n"
    .string "specializes in Pokémon aquisition!\p"
    .string "How would you like to be a member?\p"
    .string "No? Are you certain?\p"
    .string "This is the opportunity of a\n"
    ,string "lifetime. Don't miss out!\p"
    .string "I'm telling you to join!\p"
    .string "…Fine then, I'll beat you to join!\p"
    .string "I'll make you an offer you can't\n"
    .string "refuse!$"

Route24_Text_RocketDefeat::
    .string "Fucking hells!\n"
    .string "You really are prime!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "With your skill, you'd become\n"
    .string "a lieutenant in Team Rocket\l"
    .string "in no time flat\p"
    .string "If you ever change your mind!\n"
    .string "I'm pretty sure you could find us.$"

Route24_Text_ShaneIntro::
    .string "I saw you fight from the grass!$"

Route24_Text_ShaneDefeat::
    .string "You really are tough!$"

Route24_Text_ShanePostBattle::
    .string "I hid because the people on the\n"
    .string "bridge freaked me out.$"

Route24_Text_EthanIntro::
    .string "Last stop is the 5 train!\n"
    .string "End of the line for you!$"

Route24_Text_EthanDefeat::
    .string "Going too fast!\n"
    .string "Gotta pull the emergency brake!$"

Route24_Text_EthanPostBattle::
    .string "You really derailed me!$"

Route24_Text_ReliIntro::
    .string "I'm numero cuatro!\n"
    .string "Getting tired yet?$"

Route24_Text_ReliDefeat::
    .string "You did me dirty!$"

Route24_Text_ReliPostBattle::
    .string "You got the sauce kid!$"

Route24_Text_TimmyIntro::
    .string "Im the Third Amigo!\n"
    .string "I keep it real!$"

Route24_Text_TimmyDefeat::
    .string "Oof!\n"
    .string "Big sad.$"

Route24_Text_TimmyPostBattle::
    .string "You put me in my place!$"

Route24_Text_AliIntro::
    .string "I'm next up!\n"
    .string "Do you have the endurance!$"

Route24_Text_AliDefeat::
    .string "What is this feeling?$"

Route24_Text_AliPostBattle::
    .string "You really made me work!$"

Route24_Text_CaleIntro:: @ 818901B
    .string "People call this the Rival\n"
    .string "Bridge!\p"
    .string "Beat us five Trainers and win\n"
    .string "the grand prize!\p"
    .string "Let's see what you're made of$"

Route24_Text_CaleDefeat::
    .string "Gods Dammit!\n"
    .string "You really did a number on me!$"

Route24_Text_CalePostBattle::
    .string "Great job! Color me impressed.$"
