Route11_Text_HugoIntro::
    .string "Win, lose, or draw!$"

Route11_Text_HugoDefeat::
    .string "Atcha!\n"
    .string "Nani? Tondemonai!$"

Route11_Text_HugoPostBattle::
    .string "Pokémon is life!\n"
    .string "And to live is to play games!$"

Route11_Text_JasperIntro::
    .string "Competition!\n"
    .string "I can't get enough!$"

Route11_Text_JasperDefeat::
    .string "Dammit! So close!$"

Route11_Text_JasperPostBattle::
    .string "You can't be a coward in the world\n"
    .string "of Pokémon!$"

Route11_Text_EddieIntro::
    .string "Let's go, but keep it clean!$"

Route11_Text_EddieDefeat::
    .string "Huh?\n"
    .string "That's not right!$"

Route11_Text_EddiePostBattle::
    .string "I did my best.\n"
    .string "I have no regrets.$"

Route11_Text_BraxtonIntro::
    .string "Careful!\n"
    .string "I'm laying down some cables!$"

Route11_Text_BraxtonDefeat::
    .string "That was electric!$"

Route11_Text_BraxtonPostBattle::
    .string "Spread the word to save energy!\n"
    .string "Solar, wind, and hydro!$"

Route11_Text_DillonIntro:: @ 818506A
    .string "I'm abrand new Trainer.\n"
    .string "But, I think I can win.$"

Route11_Text_DillonDefeat:: @ 818509B
    .string "My Pokémon couldn't hack it…\n"
    .string "They're not strong enought yet.$"

Route11_Text_DillonPostBattle::
    .string "Thanks for the battle!\n"
    .string "I learned a lot!$"

Route11_Text_DirkIntro::
    .string "I'm the undefeated champ of\n"
    .string "Route 11!$"

Route11_Text_DirkDefeat::
    .string "Fuck! My first loss!$"

Route11_Text_DirkPostBattle::
    .string "Ugh, I'm 21-1 now.$"

Route11_Text_DarianIntro::
    .string "I've only ever lost…$"

Route11_Text_DarianDefeat::
    .string "I saw this coming…$"

Route11_Text_DarianPostBattle::
    .string "I lost… again…$"

Route11_Text_YasuIntro::
    .string "I'm the best in my class.\n"
    .string "I train every morning.$"

Route11_Text_YasuDefeat::
    .string "Damn!\n"
    .string "My Pokémon need to be stronger!$"

Route11_Text_YasuPostBattle:: @ 81851D2
    .string "There's a fat Pokémon that comes\n"
    .string "down from the mountains.\p"
    .string "I bet it'd be strong if you can\n"
    .string "catch it.$"

Route11_Text_BernieIntro::
    .string "I'm a live wire!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "You plugged my socket!$"

Route11_Text_BerniePostBattle::
    .string "Well, better get back to work.$"

Route11_Text_DaveIntro:: @ 8185285
    .string "I raised my Pokémon carefully.\n"
    .string "They should be ready by now!$"

Route11_Text_DaveDefeat::
    .string "Oof!\n"
    .string "Thank you, and good-bye!$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "I better go train up!$"

Route11_Text_DiglettsCave:: @ 8185308
    .string "Diglett's Cave$"

