CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Gamblers are so gullable!\p"
    .string "The slots just rack in the dough,\n"
    .string "big-time!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes:: @ 8197AD3
    .string "Chief!\p"
    .string "We just shipped two thousand\n"
    .string "more Pokémon as slot prizes\l"
    .string "again today! Pay day!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster:: @ 8197B20
    .string "Don't touch the poster at the\n"
    .string "Casino!\p"
    .string "There's no secret switch behind it!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of Diglett.", and is removed altogether in FRLG
Text_ItsABuddhistAltar:: @ 8197B6F
    .string "ぶつだん　だ‥$"
