Route14_Text_CarterIntro::
    .string "You need to use TMs to teach good\n"
    .string "moves to Pokémon.$"

Route14_Text_CarterDefeat::
    .string "Not good enough quite yet.$"

Route14_Text_CarterPostBattle:: @ 8185E9C
    .string "You have some HMs, right? Pokémon\n"
    .string "can't forget those moves easily.$"

Route14_Text_MitchIntro:: @ 8185EDF
    .string "My bird Pokémon should be ready\n"
    .string "for battle.$"

Route14_Text_MitchDefeat::
    .string "Not ready yet!$"

Route14_Text_MitchPostBattle:: @ 8185F1A
    .string "My bird Pokémon need to learn\n"
    .string "better moves.$"

Route14_Text_BeckIntro::
    .string "They have TMs on sale at the\n"
    .string "Celadon Dept. Store.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"

Route14_Text_BeckDefeat::
    .string "Aww, bummer!$"

Route14_Text_BeckPostBattle:: @ 8185FBB
    .string "Try teaching Pokémon a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"

Route14_Text_MarlonIntro:: @ 8186021
    .string "Have you taught your bird Pokémon\n"
    .string "how to Fly?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky!$"

Route14_Text_MarlonDefeat::
    .string "Shot down in flames!$"

Route14_Text_MarlonPostBattle:: @ 8186091
    .string "Bird Pokémon are my one true love.\n"
    .string "I don't want to raise anything else.$"

Route14_Text_DonaldIntro::
    .string "Have you heard the legend of the\n"
    .string "winged mirages?$"

Route14_Text_DonaldDefeat::
    .string "Why?\n"
    .string "Why'd I lose?$"

Route14_Text_DonaldPostBattle::
    .string "Well, the winged mirages are the\n"
    .string "legendary bird Pokémon.\p"
    .string "There are three of them: Articuno,\n"
    .string "Zapdos, and Moltres.$"

Route14_Text_BennyIntro::
    .string "I'm not into it, but okay.\n"
    .string "Let's go!$"

Route14_Text_BennyDefeat::
    .string "I knew it!$"

Route14_Text_BennyPostBattle::
    .string "Winning, losing… It's insignificant\n"
    .string "under this huge sky.$"

Route14_Text_LukasIntro::
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Lost! Get lost!$"

Route14_Text_LukasPostBattle::
    .string "What, what, what?\n"
    .string "What do you want still?$"

Route14_Text_IsaacIntro::
    .string "I need to burn some time.\n"
    .string "Shut up and battle.$"

Route14_Text_IsaacDefeat::
    .string "What?\n"
    .string "You!?$"

Route14_Text_IsaacPostBattle:: @ 818629D
    .string "Raising Pokémon is a drag, man.$"

Route14_Text_GeraldIntro::
    .string "We ride out here because of the\n"
    .string "wide-open spaces.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle:: @ 81862F8
    .string "It's cool you made your Pokémon so\n"
    .string "strong.\p"
    .string "Might is right!\n"
    .string "And you know it!$"

Route14_Text_MalikIntro:: @ 8186344
    .string "Pokémon battle?\n"
    .string "Cool! Rumble!$"

Route14_Text_MalikDefeat::
    .string "Blown away!$"

Route14_Text_MalikPostBattle::
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"

Route14_Text_RouteSign:: @ 8186399
    .string "Route 14\n"
    .string "West to Fuchsia City$"

Route14_Text_KiriIntro:: @ 81863B7
    .string "Kiri: Jan, let's try really,\n"
    .string "really hard together.$"

Route14_Text_KiriDefeat:: @ 81863EA
    .string "Kiri: Whimper…\n"
    .string "We lost, didn't we?$"

Route14_Text_KiriPostBattle:: @ 818640D
    .string "Kiri: Did we lose because of me?$"

Route14_Text_KiriNotEnoughMons:: @ 818642E
    .string "Kiri: We can battle if you have\n"
    .string "two Pokémon.$"

Route14_Text_JanIntro:: @ 818645B
    .string "Jan: Kiri, here we go!\n"
    .string "We have to try hard!$"

Route14_Text_JanDefeat:: @ 8186487
    .string "Jan: Eeeeh!\n"
    .string "No fair!$"

Route14_Text_JanPostBattle:: @ 818649C
    .string "Jan: Kiri, don't cry!\n"
    .string "We'll just try harder next time.$"

Route14_Text_JanNotEnoughMons:: @ 81864D3
    .string "Jan: You want to battle?\n"
    .string "You don't have enough Pokémon.$"
