ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "...existential crisis...\n"
    .string "...existential crisis...$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "I wish I had a glass of wine...$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Haha, Poké Balls are a funny name\n"
    .string "I wonder if they shrink in the cold\p"
    .string "Yeah, yeah, I know I can use them\n"
    .string "to catch them. Everyone does.\p"
    .string "Why am I learning all this\n"
    .string "common knowledge.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "Beat up a mon before catching.\n"
    .string "lol, this seems so easy.\p"
    .string "take em out with damage or\n"
    .string "statuses before catching.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "Trainers use Pokémon to fight!?\n"
    .string "This seems barbaric. Do they wanna?\p"
    .string "Do Pokémon have a choice?\n"
    .string "This is horrible...\p"
    .string "What kind of sick world is this?\n"
    .string "I don't know if I can handle it.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "So you have to beat up eight\n"
    .string "gym leaders to get badges.\p"
    .string "And then fight the Elite Four\n"
    .string "to become champion?\p"
    .string "How many Pokémon must fall?\p"
    .string "How much needless pain and\n"
    .string "suffering. Why.......$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes:: @ 818FF28
    .string "Girl: Get out...\n"
    .string "While you still can!$"

ViridianCity_School_Text_BlackboardListsStatusProblems:: @ 818FF4B
    .string "The blackboard has scribbles of\n"
    .string "Status problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep:: @ 818FFA9
    .string "A Pokémon can't attack if it's\n"
    .string "sleeping. Why did you even ask?\p"
    .string "Pokémon will stay asleep even\n"
    .string "after battles.\p"
    .string "Use Awakening to awaken one\n"
    .string "from sleep. It's obvious.$"

ViridianCity_School_Text_ExplainBurn:: @ 8190025
    .string "A burn reduces Attack power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use Burn Heal to cure a burn.$"

ViridianCity_School_Text_ExplainPoison:: @ 819009F
    .string "When poisoned, a Pokémon's health\n"
    .string "drops. Like Romeo and Juliet\p"
    .string "Poison lingers after battles.\n"
    .string "Use an Antidote to cure poison.$"

ViridianCity_School_Text_ExplainFreeze:: @ 819010F
    .string "A frozen Pokémon becomes\n"
    .string "...frozen. Just let it go.\p"
    .string "It stays frozen even after the\n"
    .string "battle. Like Olaf in summer.\p"
    .string "Use Ice Heal to thaw out the\n"
    .string "Iciclemon.$"

ViridianCity_School_Text_ExplainParalysis:: @ 8190199
    .string "Paralysis is self explanitory\n"
    .string "it prevents Pokémon from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use an item to heal...I don't know.$"

