SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "This ship, she is a luxury liner for\n"
    .string "Trainers of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited Trainers.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Yo! Dickhead!\n"
    .string "{PLAYER}!\p"
    .string "Imagine seeing you here!\n"
    .string "{PLAYER}, how'd YOU get an invite?\p"
    .string "Wait, you helped Bill?\p"
    .string "HE WAS A POKéMON?!\n"
    .string "That's fucking wild.\p"
    .string "Well, you know what time it is.\n"
    .string "Put up them dukes!$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Pfft! Whatever!\p"
    .string "At least you're a decent\n"
    .string "Rival...$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle:: @ 8173164
    .string "{RIVAL}: I heard there was an Cut\n"
    .string "master on board.\p"
    .string "But he was just a seasick old man!\p"
    .string "Really stupid when you're the\n"
    .string "Captain...\p"
    .string "Anyway, you should pick it up.\n"
    .string "Till the next time asshat!$"

