Route10_Text_MarkIntro::
    .string "Wow, you came all the way over here?\n"
    .string "Maybe you're a Pokémaniac, too?\l"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat::
    .string "UGH!$"

Route10_Text_MarkPostBattle:: @ 8184BFB
    .string "I have more rare Pokémon at home!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Ha-ha! Haha-ha-ha!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-ha!\n"
    .string "cough-cough!\l"
    .string "BWAHAHAHAHAHA!$"

Route10_Text_HermanIntro::
    .string "Hey, kid!\n"
    .string "Want to see my Pokémon?$"

Route10_Text_HermanDefeat::
    .string "Oh, no!\n"
    .string "My Pokémon!$"

Route10_Text_HermanPostBattle::
    .string "I don't like you!$"

Route10_Text_HeidiIntro:: @ 8184CF1
    .string "I've been out at a Pokémon Gym\n"
    .string "a few times.\p"
    .string "…But I always lose.$"

Route10_Text_HeidiDefeat::
    .string "God dammit!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle:: @ 8184D4D
    .string "I noticed some Pokémaniacs\n"
    .string "prowling around.\p"
    .string "Can you imagine? Them?\n"
    .string "Up here in the mountains?$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "This mountain air is delicious!$"

Route10_Text_TrentDefeat::
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle::
    .string "Mountain are is my therapy!$"

Route10_Text_CarolIntro::
    .string "I'm feeling a bit faint.\n"
    .string "I haven't hiked in a minute.$"

Route10_Text_CarolDefeat::
    .string "Ugh, I'm too tired.\n"
    .string "I wasn't up for this.$"

Route10_Text_CarolPostBattle:: @ 8184E5E
    .string "The Pokémon here in the mountains\n"
    .string "are so chunky…\p"
    .string "I wish there were pink Pokémon\n"
    .string "with a floral pattern here!$"

Route10_Text_RockTunnelDetourToLavender:: @ 8184EC5
    .string "Rock Tunnel\n"
    .string "Detour to Lavender Town$"

Route10_Text_RockTunnel:: @ 8184EE9
    .string "Rock Tunnel$"

Route10_Text_PowerPlant:: @ 8184EF5
    .string "Power Plant$"

