
RockTunnel_1F_Text_LennyIntro::
    .string "This tunnel goes a long way, kid!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "Woah!\n"
    .string "You win!$"

RockTunnel_1F_Text_LennyPostBattle:: @ 8179396
    .string "Watch out for Onix.\n"
    .string "They appear occasionally.\p"
    .string "High-level ones can put the\n"
    .string "squeeze on you!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm.\n"
    .string "Maybe I'm lost in here…$"

RockTunnel_1F_Text_OliverDefeat::
    .string "Ease up!\n"
    .string "Which way is out?$"

RockTunnel_1F_Text_OliverPostBattle:: @ 817943A
    .string "That sleeping Pokémon on Route 12\n"
    .string "forced me to take this detour.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Outsiders like you need to show me\n"
    .string "some respect!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "I give!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "You're talented enough to hike!$"

RockTunnel_1F_Text_AshtonIntro:: @ 81794D4
    .string "Enter Credits!\n"
    .string "A New Challanger Approachs!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "Game over, man! GAME OVER!$"

RockTunnel_1F_Text_AshtonPostBattle:: @ 81794F9
    .string "I need to work on my arcade skills!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Eek!\p"
    .string "Don't try anything funny in the\n"
    .string "dark!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "It was too dark…$"

RockTunnel_1F_Text_LeahPostBattle:: @ 8179558
    .string "So many creeps about.$"

RockTunnel_1F_Text_DanaIntro::
    .string "I came here looking for wild\n"
    .string "Pokémon.$"

RockTunnel_1F_Text_DanaDefeat:: @ 81795A1
    .string "I'm out of Pokémon!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "You looked cute and harmless.\n"
    .string "Was I ever wrong!$"

RockTunnel_1F_Text_ArianaIntro:: @ 81795E5
    .string "You have Pokémon!\n"
    .string "Let's start!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "You play hard!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Whew!\n"
    .string "That was exhausting.$"

RockTunnel_1F_Text_RouteSign:: @ 817962D
    .string "Rock Tunnel\n"
    .string "Cerulean City - Lavender Town$"

