Debug_MapScripts::
	.byte 0


Debug_Veridian::
	msgbox Debug_Veridian_Text_0,	MSGBOX_SIGN
	end


Debug_Pewter::
	msgbox Debug_Pewter_Text_0,	MSGBOX_SIGN
	end


Debug_Cerulean::
	msgbox Debug_Cerulean_Text_0,	MSGBOX_SIGN
	end


Debug_Lavender::
	msgbox Debug_Lavender_Text_0,	MSGBOX_SIGN
	end


Debug_Vermilion::
	msgbox Debug_Vermilion_Text_0,	MSGBOX_SIGN
	end


Debug_Celadon::
	msgbox Debug_Celadon_Text_0,	MSGBOX_SIGN
	end


Debug_Fuchsia::
	msgbox Debug_Fuchsia_Text_0,	MSGBOX_SIGN
	end


Debug_Cinnebar::
	msgbox Debug_Cinnebar_Text_0,	MSGBOX_SIGN
	end


Debug_Saffron::
	msgbox Debug_Saffron_Text_0,	MSGBOX_SIGN
	end


Debug_Pallet::
	msgbox Debug_Pallet_Text_0,	MSGBOX_SIGN
	end


Debug_Veridian_Text_0:
	.string "Veridian City.$"

Debug_Pewter_Text_0:
	.string "Pewter City.$"

Debug_Cerulean_Text_0:
	.string "Cerulean City.$"

Debug_Lavender_Text_0:
	.string "Lavender Town.$"

Debug_Vermilion_Text_0:
	.string "Vermilion City.$"

Debug_Celadon_Text_0:
	.string "Celadon City.$"

Debug_Fuchsia_Text_0:
	.string "Fuchsia City.$"

Debug_Cinnebar_Text_0:
	.string "Cinnebar Island.$"

Debug_Saffron_Text_0:
	.string "Saffron City.$"

Debug_Pallet_Text_0:
	.string "Pallet Town.$"
