Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hold on! Where's my script? AHA!\n"
    .string "Hi, I work at the PokéMart.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in Viridian City.\p"
    .string "Here is a sample just for you.\n"
    .string "Hope to see you in our stores!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "I get nervous speaking to people\n"
    .string "so I have to write it down to\l"
    .string "make it easier.$"

Route1_Text_PutPotionAway:: @ 8183387
    .string "{PLAYER} put the Potion away in\n"
    .string "the Bag's Items Pocket.$"

Route1_Text_CanJumpFromLedges::
    .string "Shhh, be very quiet.\p"
    .string "I'm looking for an Eevee.\n"
    .string "I heard they come here sometimes.\p"
    .string "Maybe its not true but I\n"
    .string "might as well find out.$"

Route1_Text_RouteSign:: @ 818343A
    .string "Route 1\n"
    .string "Pallet Town - Viridian City$"

