PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou:: @ 818D2F0
    .string "Mom: It's about time you\n"
    .string "left the house.\p"
    .string "Always upstairs playing\n" 
    .string "video games.\p"
    .string "By the way, Prof. Oak, next door\n"
    .string "was looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou:: @ 818D360
    .string "Mom: Hey honey. Are you\n"
    .string "all packed and ready to go?\l"
    .string "Be safe on your adventure!\p"
    .string "By the way, Prof. Oak, next door\n"
    .string "was looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest:: @ 818D3D1
    .string "Mom: {PLAYER}! Come, relax.\n"
    .string "Spend time with your mom.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare:: @ 818D3F8
    .string "Mom: Oh, good! You and your\n"
    .string "Pokémon are looking amazing.\l"
    .string "Take care, love you!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Die Hard, my favorite Christmas\l"
    .string "movie. Yippie-Ki-Yay!\p"
    .string "…I better go$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "The Notebook. Why are they\l"
    .string "standing in the rain?\p"
    .string "…I better go.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

