RocketHideout_B3F_Text_Grunt1Intro:: @ 817511A
    .string "Hey kid! Stay out of our\n"
    .string "business or else!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Oof!\n"
    .string "That one stung!$"

RocketHideout_B3F_Text_Grunt1PostBattle:: @ 817515B
    .string "Silph Scope?\n"
    .string "Oh, that machine the Boss stole.\p"
    .string "Like I'd tell you...$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "We got word from my homies\n"
    .string "upstairs that you were coming!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "Gods dammit! They told\n"
    .string " me not to underestimate you...!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "Get! Fuckin' kid.\p"
    .string "Doesn't matter\n"
    .string "without the Lift Key.$"

