SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies:: @ 819C023
    .string "Pokémon growth rates differ from\n"
    .string "species to species.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame:: @ 819C058
    .string "Silph Co. is widely known to all.\p"
    .string "Team Rocket took over because it's\n"
    .string "the largest tech company in Kanto.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Sigh…\n"
    .string "Wouldn't it be great if\l"
    .string "If the Elite Four came and\l"
    .string "stomped out Team Rocket?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff:: @ 819C102
    .string "Team Rocket took off!\n"
    .string "We can go out safely again!\l"
    .string "That's great!$"

