PokemonTower_1F_Text_ErectedInMemoryOfDeadMons:: @ 8179B7A
    .string "Pokémon Tower was built in the\n"
    .string "memory of Pokémon that have passed.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "Bless your Pokémon-loving heart,\n"
    .string "young man.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your Pokémon-loving heart,\n"
    .string "young lady.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I came to visit my dearly\n"
    .string "departed Clefairy.\p"
    .string "Sniff!\n"
    .string "I can't stop crying…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie:: @ 8179C8C
    .string "My Growlithe…\n"
    .string "Why did you leave me?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief:: @ 8179CAB
    .string "I am a Channeler.\p"
    .string "There are spirits up to mischief.\n"
    .string "I sense them high in the Tower.$"

