CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "Still eating my dust I see.\n"
    .string "Having trouble keeping up?\p"
    .string "I'm doing great! I caught a bunch\n"
    .string "of strong and smart Pokémon!\p"
    .string "Here, let me see what you caught,\n"
    .string "loser!$"

CeruleanCity_Text_RivalDefeat::
    .string "Come on!\n"
    .string "No need to go so hard!\l"
    .string "Shit!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, guess what?\p"
    .string "I went to Bill's and got him to\n"
    .string "show me his rare Pokémon.\p"
    .string "That added a lot of pages to my\n"
    .string "Pokédex!\p"
    .string "After all, Bill's world famous as a\n"
    .string "Pokémaniac.\p"
    .string "I guess since you're already out\n"
    .string "here you might as well visit.\p"
    .string "Also he invented the PC Storage,\n"
    .string "and you should go thank him.\p"
    .string "Well, I better go keep winning!\n"
    .string "Smell ya later, assbutt!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, by the way.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always five steps behind.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "For a gossip like you…\n"
    .string "That's a perfect gift.\p"
    .string "I don't need it because I don't\n"
    .string "give a hoot about others.\p"
    .string "All right, this time I really am\n"
    .string "gone. Smell ya!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Get out!\n"
    .string "This isn't your yard!\p"
    .string "…What?\n"
    .string "Who me?\p"
    .string "I'm just an innocent bystander!\n"
    .string "Fine then, I'll just beat your ass?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat:: @ 817EE70
    .string "Grunt: Stop! Fuck!\n"
    .string "I'll go, shit!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…What? Ugh, you're such a snob.\n"
    .string "Fine, I'll return the TM.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} recovered TM28 from\n"
    .string "the Team Rocket Grunt.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "I'm out before that hot cop comes!\n"
    .string "Laters!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Are you serious!\n"
    .string "Take it so I can dip!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt:: @ 817EF3F
    .string "You're a Trainer, too?\p"
    .string "Collecting, battling…\n"
    .string "It's awesome isn't it?!$"

CeruleanCity_Text_YouCanCutDownSmallTrees:: @ 817EF89
    .string "You see that small tree?\n"
    .string "Yes, the one in front of the shop?\p"
    .string "If you cut it down there\n"
    .string "is a neat little shortcut.\p"
    .string "There's a way around it, though.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree:: @ 817F01D
    .string "SLOWBRO! Get out of the way!\n"
    .string "People are trying to cut the tree.\p"
    .string "Come on! Please listen!\n"
    .string "Ugh!\p"
    .string "I'm so sorry. He is a bit\n"
    .string "slow on the uptake.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "You're making an encyclopedia on\n"
    .string "Pokémon? That's kinda nerdy, innit?$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "Officer Jenny: There was a\n"
    .string "robbery here. Team Rocket is\l"
    .string "definitely behind this crime!\p"
    .string "Our Police Force has had\n"
    .string "trouble with the Rockets!$"

CeruleanCity_Text_SlowbroUseSonicboom:: @ 817F183
    .string "Okay! Guile, I mean Slowbro!\n"
    .string "Use SonicBoom!$"

CeruleanCity_Text_SlowbroPayAttention:: @ 817F1A1
    .string "Come on, Slowbro, pay attention!$"

CeruleanCity_Text_SlowbroPunch:: @ 817F1C2
    .string "Slowbro, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "Ugh!\n"
    .string "You blew it again!$"

CeruleanCity_Text_SlowbroWithdraw:: @ 817F1E9
    .string "Slowbro, Withdraw!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "No! That's wrong!\n"
    .string "It's hard to control some Pokémon!\p"
    .string "My Slowbro is a bit more stubborn\n"
    .string "than my other Pokémon.$"

CeruleanCity_Text_SlowbroTookSnooze:: @ 817F270
    .string "Slowbro fell asleep…$"

CeruleanCity_Text_SlowbroLoafingAround:: @ 817F287
    .string "Slowbro is chillin…$"

CeruleanCity_Text_SlowbroTurnedAway:: @ 817F2A2
    .string "Slowbro looked off into the sky…$"

CeruleanCity_Text_SlowbroIgnoredOrders:: @ 817F2B7
    .string "Slowbro yawned…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "I want a bright red bicycle.\p"
    .string "I'll keep it at home, so it won't\n"
    .string "get dirty.$"

CeruleanCity_Text_ThisIsCeruleanCave:: @ 817F319
    .string "This is The Cerulean Cave.\p"
    .string "Horribly strong Pokémon live inside\n"
    .string "there.\p"
    .string "Come back when you've trained up\n"
    .string "a bit.$"

CeruleanCity_Text_CitySign:: @ 817F420
    .string "Cerulean City\n"
    .string "A Mysterious, Blue Aura Surrounds\l"
    .string "It$"

CeruleanCity_Text_TrainerTipsHeldItems:: @ 817F453
    .string "Trainer Tips\p"
    .string "If you're having an issue\n"
    .string "trying to catch a Pokémon\p"
    .string "Maybe you should just try\n"
    .string "catching it, it't that simple.$"

CeruleanCity_Text_BikeShopSign::
    .string "The Number one Bike Shop!\n"
    .string "in Kanto!$"

CeruleanCity_Text_GymSign:: @ 817F4EF
    .string "Cerulean City Pokémon Gym\n"
    .string "Leader: Misty\l"
    .string "The Cerulean Mermaid!$"

