PewterCity_House1_Text_Nidoran:: @ 81915BB
    .string "Nidoran♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit:: @ 81915CD
    .string "Nidoran, sit!$"

PewterCity_House1_Text_TradeMonsAreFinicky:: @ 81915DB
    .string "We spend a good amount of time\n"
    .string "training and caring for Nidoran.\p"
    .string "He is a rescue Pokémon that we were\n"
    .string "able to care for after he was abused.\p"
    .string "Team Rocket is a menace and really\n"
    .string "hurt Pokémon. Justice will eventually\p"
    .string "come for them and they will go down…$"

