ViridianCity_Text_CanCarryMonsAnywhere:: @ 817DABB
    .string "Those Poké Balls at your waist!\n"
    .string "By Arceus! You're a Trainer?\p"
    .string "It's great that you can carry and\n"
    .string "use Pokémon. They're the best.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs:: @ 817DB39
    .string "This Pokémon Gym is always closed.\p"
    .string "This is just bad for the economy!$"

ViridianCity_Text_ViridiansGymLeaderReturned:: @ 817DB78
    .string "Viridian Gym's Leader returned!\p"
    .string "Finally, just what the local\n"
    .string "economy needed!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "Hey, do you wanna learn about\n"
    .string "kinds of caterpillar Pokémon?$"

ViridianCity_Text_OhOkayThen::
    .string "Pfft! Fine then!$"

ViridianCity_Text_ExplainCaterpieWeedle:: @ 817DBE4
    .string "Caterpie has no poison,\n"
    .string "but Weedle does.\p"
    .string "Watch that your Pokémon aren't\n"
    .string "stabbed by Weedle's Poison Sting.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Dammit, Grandpa!\n"
    .string "Don't be so savage!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally:: @ 817DC99
    .string "I go shopping in Pewter City\n"
    .string "occasionally.\p"
    .string "I have to take the trail in\n"
    .string "Viridian Forest to get there.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Get outta here! Git! No\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that device you have?\p"
    .string "Ah, so you're working on your\n"
    .string "Pokédex. Very neat.\p"
    .string "Let me give you a word of\n"
    .string "advice. What I wish I knew.\p"
    .string "Whenever you catch a Pokémon,\n"
    .string "the Pokédex automatically updates\l"
    .string "its data. Fancy technology, huh?\p"
    .string "…Wait a damn minute. You don't\n"
    .string "know how to catch a Pokémon?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "SHIT! Threw out my back tossin\n"
    .string "that Poké Ball.\p"
    .string "Ow. Here, take this.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "know, just turn it on and watch.\p"
    .string "It'll teach you all the basics\n"
    .string "of being a Pokémon Trainer.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee,\n"
    .string "I feel like I can hear colors!\p"
    .string "I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "By the way, how's it going\n"
    .string "filling up your Pokédex?\p"
    .string "Always make sure to weaken the\n"
    .string "Pokémon before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee,\n"
    .string "I feel like I can taste sound!\p"
    .string "I made it too strong.\n"
    .string "Now I have to run to the toilet…\p"
    .string "Also, is my old Teachy TV helping\n"
    .string "you? Neat little device it is.$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Would you look at that!\n"
    .string "My grandson's on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for Teachy TV…\p"
    .string "Time is money, and neither should\n"
    .string "spent on frivulous things…$"

ViridianCity_Text_CitySign:: @ 817E1BB
    .string "Viridian City \n"
    .string "The Green Dream.$"

ViridianCity_Text_CatchMonsForEasierBattles:: @ 817E1E7
    .string "Trainer Tips\p"
    .string "Make sure to take a break and\n"
    .string "stay hydrated.\p"
    .string "You can't catch them all if you're\n"
    .string "too thirsty.$"

ViridianCity_Text_MovesLimitedByPP:: @ 817E24D
    .string "Trainer Tips\p"
    .string "Don't be like Markiplier and try\n"
    .string "to Smash or Pass Pokémon.\p"
    .string "That's a sure fire way to end\n"
    .string "up dead or in jail.$"

ViridianCity_Text_GymSign:: @ 817E2DB
    .string "Viridian City Pokémon Gym$"

ViridianCity_Text_GymDoorsAreLocked:: @ 817E2F5
    .string "Viridian Gym's doors are locked…$"

