VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "Aww man!\n" 
	.string "I really want a {STR_VAR_1}.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…This is not a {STR_VAR_1}.\p"
	.string "Don't try and play me!\n"
	.string "I can't believe you!$"

VermilionCity_House2_Text_ThankYou::
	.string "Thanks!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "How is {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is amazing!$"
