CeladonCity_Text_GotMyKoffingInCinnabar:: @ 817FEC3
    .string "I caught my Koffing at Cinnabar.\p"
    .string "It's usually chill but breathes\n"
    .string "poison when it's upset.$"

CeladonCity_Text_GymIsGreatFullOfWomen:: @ 817FF1C
    .string "Ohoho! This Gym is great!\n"
    .string "It's full of women!$"

CeladonCity_Text_GameCornerIsBadForCitysImage:: @ 817FF4A
    .string "Celadon takes pride in its efforts\n"
    .string "to keep the city beautiful.\p"
    .string "That's why the new Casino is\n"
    .string "bad for our city's image.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Ugh…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I should have cashed out!$"

CeladonCity_Text_MyTrustedPalPoliwrath:: @ 818001B
    .string "This is my buddy, Poliwrath.\p"
    .string "It evolved from a Poliwhirl when\n"
    .string "I used a Water Stone.$"

CeladonCity_Text_Poliwrath:: @ 8180075
    .string "Poliwrath: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Whatcha lookin' at?\n"
    .string "Beat it before I beat you.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay:: @ 81800C2
    .string "Stay outta Team Rocket's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit:: @ 81800E1
    .string "Trainer Tips\p"
    .string "Instead of looking here for\n"
    .string "techniques.\p"
    .string "How about you go out there and\n"
    .string "actually play the game?\p"
    .string "I never read these as a kid and\n"
    .string "I'm sure you didn't either!$"

CeladonCity_Text_CitySign:: @ 818017A
    .string "Celadon City\n"
    .string "Prideful City of Rainbows$"

CeladonCity_Text_GymSign:: @ 81801A2
    .string "Celadon City Pokémon Gym\n"
    .string "Leader: Erika\l"
    .string "The Tree-hugging Queen!$"

CeladonCity_Text_MansionSign:: @ 81801E5
    .string "Celadon Mansion$"

CeladonCity_Text_DeptStoreSign::
    .string "Capitalist Capital of Kanto\n"
    .string "Celadon Dept. Store!$"

CeladonCity_Text_GuardSpecProtectsFromStatus:: @ 8180224
    .string "Trainer Tips\p"
    .string "Don't...$"

CeladonCity_Text_PrizeExchangeSign:: @ 81802A4
    .string "Prize Exchange$"

CeladonCity_Text_GameCornerSign:: @ 81802CF
    .string "Rocket Casino\n"
    .string "The playground for adults!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Hot damn!…\n"
    .string "I burned my tongue!\p"
    .string "This lady in the Mansion\n"
    .string "gave me some Tea.\p"
    .string "But it was boiling hot!\n"
    .string "Gotta blow on it first.$"

Text_SoftboiledTeach::
    .string "Hello there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be the force that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move Softboiled.$"

Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

Text_SoftboiledWhichMon:: @ 8180484
    .string "So, who's the Pokémon that gets\n"
    .string "the chance to learn SoftBoiled?$"

Text_SoftboiledTaught::
    .string "Best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Fuck, what am I gonna do…\p"
    .string "Someone stole the Silph Scope.\p"
    .string "The asshat came running this way.\n"
    .string "I'm sure of it.\p"
    .string "But I lost him!\n"
    .string "I'm so gonna lose my job!$"

