ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey! {PLAYER}, good to see you\n"
    .string "Can you do me a solid?$"

ViridianCity_Mart_Text_TakeThisToProfOak:: @ 819023A
    .string "You know Prof. Oak, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk:: @ 8190289
    .string "{PLAYER} received Oak's Parcel\n"
    .string "from the Pokémon Mart clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "You are a life saver!\n"
    .string "Thanks!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Why are you talking to me?\n"
    .string "...$"

ViridianCity_Mart_Text_GotToBuySomePotions:: @ 819032C
    .string "Potions...potions...potions....\p"
    .string "I'm looking for a special brand,\n"
    .string "Its my brand!$"

