Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze:: @ 819D52C
    .string "Going into Viridian Forest?\n"
    .string "It's a labyrinth, and not the\l"
    .string "fun kind with David Bowie.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite:: @ 819D58B
    .string "Rattata is small, but don't\n"
    .string "underestimate its chompers.\p"
    .string "You'll end up with nine fingers.$"

