CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "I'm getting a present for my\n"
    .string "girlfriend.\p"
    .string "I guess a Poké Doll will do.\n"
    .string "Or maybe I should get some flowers.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "I heard something useful.\p"
    .string "If a wild Pokémon appears, you can\n"
    .string "distract it with a Poké Doll.\p"
    .string "You can run away while the\n"
    .string "Pokémon is distracted.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Express yourself with gifts!\n"
    .string "4F: Wise Man Gifts\p"
    .string "Evolution Special!\n"
    .string "Element Stones on sale now!$"
