ViridianCity_House_Text_NicknamingIsFun::
    .string "Coming up with nicknames is fun,\n"
    .string "but it's do tough!\p"
    .string "Clever names are nice, but simple\n"
    .string "names are easier to remember.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo:: @ 818F30F
    .string "My dad loves Pokémon, too.$"

ViridianCity_House_Text_Speary:: @ 818F32C
    .string "Speary: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary:: @ 818F33D
    .string "Spearow\n"
    .string "Name: Speary$"

