PalletTown_Text_OakDontGoOut:: @ 817D72C
    .string "Oak: Hey! Wait!\n"
    .string "Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon:: @ 817D74A
    .string "Oak: It's not safe!\n"
    .string "Wild Pokémon live in tall grass!\p"
    .string "You'll need your own Pokémon for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Come along now, {PLAYER}!$"

PalletTown_Text_RaisingMonsToo:: @ 817D7C8
    .string "I'm gonna be a Pokémon Trainer.\p"
    .string "I wanna be the very best,\n"
    .string "that no one ever was.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Kids and thier technodoodles!\p"
    .string "Back in my day we used to have\n"
    .string "to carry all our items and\l"
    .string "Pokémon on our backs.$"

PalletTown_Text_OakPokemonResearchLab:: @ 817D866
    .string "Oak Pokémon Research Lab$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign:: @ 817D895
    .string "Pallet Town\n"
    .string "Shades of a Hero's town!$"

PalletTown_Text_OakLetMeSeePokedex:: @ 817D8BF
    .string "Oak: Ah, {PLAYER}!\n"
    .string "You're back, great!\p"
    .string "How much have you filled your\n"
    .string "Pokédex?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling:: @ 817DA16
    .string "Oak: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.$"
